### ISSUE TITLE
PF8: Auditing log shows MAC Auth but not 802.1x

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3050] opened 2018-03-27 21:22 UTC
Testing wired 802.1x and MAC auth. In auditing tab, I can see the MAC Auth entries, but not the 802.1x, even though I successfully logged in with 802.1x user account.

radius.log:
```
Mar 27 17:19:10 localhost auth[7060]: rlm_rest (rest): Closing connection (8): Hit idle_timeout, was idle for 71 seconds
Mar 27 17:19:10 localhost auth[7060]: rlm_rest (rest): Closing connection (9): Hit idle_timeout, was idle for 71 seconds
Mar 27 17:19:10 localhost auth[7060]: rlm_rest (rest): Opening additional connection (10), 1 of 64 pending slots used
Mar 27 17:19:11 localhost auth[7060]: Need 2 more connections to reach min connections (3)
Mar 27 17:19:11 localhost auth[7060]: rlm_rest (rest): Opening additional connection (11), 1 of 63 pending slots used
Mar 27 17:19:11 localhost auth[7060]: Need 1 more connections to reach min connections (3)
Mar 27 17:19:11 localhost auth[7060]: rlm_sql (sql): Opening additional connection (15), 1 of 62 pending slots used
Mar 27 17:19:11 localhost auth[7060]: (171)   Login OK: [atran] (from client 172.21.2.3 port 50012 cli 90:e6:ba:70:e7:4b via TLS tunnel)
Mar 27 17:19:11 localhost auth[7060]: [mac:90:e6:ba:70:e7:4b] Accepted user:  and returned VLAN 20
Mar 27 17:19:11 localhost auth[7060]: (172) Login OK: [atran] (from client 172.21.2.3 port 50012 cli 90:e6:ba:70:e7:4b)
```

Audit page:
![image](https://user-images.githubusercontent.com/36165527/37995730-67711c2a-31e3-11e8-95e3-629330bb7cb6.png)

**Comment by extrafu** [comment] 2018-03-27 21:26
@atran-inverse  Do you have errors in packetfence.log at the same time?

**Comment by atran-inverse** [comment] 2018-03-27 21:30
This is from packetfence.log with the same timestamp. The only error seems to be related to fingerbank.
```
Mar 27 17:19:10 localhost pfqueue: pfqueue(8498) INFO: [mac:90:e6:ba:70:e7:4b] deauthenticating (pf::Switch::Cisco::Catalyst_2960::radiusDisconnect)
Mar 27 17:19:10 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] handling radius autz request: from switch_ip => (172.21.2.3), connection_type => Ethernet-EAP,switch_mac => (00:17:e0:c2:93:0c), mac => [90:e6:ba:70:e7:4b], port => 10012, username => "atran" (pf::radius::authorize)
Mar 27 17:19:10 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
Mar 27 17:19:10 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Found authentication source(s) : 'InverseAD' for realm 'null' (pf::config::util::filter_authentication_sources)
Mar 27 17:19:10 localhost packetfence_httpd.aaa: httpd.aaa(12918) WARN: [mac:90:e6:ba:70:e7:4b] Calling match with empty/invalid rule class. Defaulting to 'authentication' (pf::authentication::match2)
Mar 27 17:19:10 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Using sources InverseAD for matching (pf::authentication::match2)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Matched rule (catchall) in source InverseAD, returning actions. (pf::Authentication::Source::match)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Found authentication source(s) : 'InverseAD' for realm 'null' (pf::config::util::filter_authentication_sources)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Using sources InverseAD for matching (pf::authentication::match2)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Matched rule (catchall) in source InverseAD, returning actions. (pf::Authentication::Source::match)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Username was defined "atran" - returning role 'default' (pf::role::getRegisteredRole)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] PID: "atran", Status: reg Returned VLAN: (undefined), Role: default (pf::role::fetchRoleForNode)
Mar 27 17:19:11 localhost pfqueue: pfqueue(8349) INFO: [mac:unknown] Already did a person lookup for atran (pf::lookup::person::lookup_person)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] (172.21.2.3) Added VLAN 20 to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] violation 1300003 force-closed for 90:e6:ba:70:e7:4b (pf::violation::violation_force_close)
Mar 27 17:19:11 localhost packetfence_httpd.aaa: httpd.aaa(12918) INFO: [mac:90:e6:ba:70:e7:4b] Instantiate profile 802.1x (pf::Connection::ProfileFactory::_from_profile)
Mar 27 17:19:11 localhost pfqueue: pfqueue(8340) ERROR: [mac:90:e6:ba:70:e7:4b] Error while communicating with the Fingerbank collector. 400 Can't locate object method "scheme" via package "URI::https" (pf::fingerbank::endpoint_attributes)
Mar 27 17:19:11 localhost pfqueue: pfqueue(8340) ERROR: [mac:90:e6:ba:70:e7:4b] Unable to fetch query arguments for Fingerbank query. Aborting. (pf::fingerbank::process)
```

**Comment by extrafu** [comment] 2018-03-27 21:33
Thanks @atran-inverse  - assigning to @jrouzierinverse

**Comment by extrafu** [comment] 2018-03-28 19:09
I can confirm this bug. When entering the Auditing module, pfconfig spews this into logs:

Mar 28 15:08:44 localhost pfconfig: pfconfig(1125) ERROR: [mac:[undef]] Unknown index in resource::authentication_sources;9 (main::get_array_element)

**Comment by extrafu** [comment] 2018-03-28 19:10
@julsemaan You might want to look into the pfconfig error.

**Comment by julsemaan** [comment] 2018-03-28 20:51
The pfconfig error doesn't seem to have an impact on that and to be a coincidence.

The issue is that the 802.1x RADIUS audit log records have a tenant ID value of 0 instead of 1.

@jrouzierinverse, could you look into that part ?

**Comment by jrouzierinverse** [comment] 2018-03-29 18:37
Try 4f0a4d780522e94dd9aa01f6ec067ab6dcf4eddd to see if it fixes it.
If it is applied manually remember to copy conf/radiusd/packetfence-tunnel.example to conf/radiusd/packetfence-tunnel

**Comment by extrafu** [comment] 2018-03-30 13:27
Works for me now, closing.

**Closed as completed by extrafu** 2018-03-30 13:27 UTC
Labels: Type: Bug, Priority: High
