### ISSUE TITLE
maintenance/9.0: Bug when navigating next page in nodes

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4690] opened 2019-07-25 15:22 UTC
**Describe the bug**
When navigating the next page on the nodes, you are brought back to the first page every time the amount of pages goes higher than the one that is already there (so when it expands from 2 to 3 pages, 3 to 4, etc)

**To Reproduce**
1. Go in the nodes
2. Click on page 2
3. You're back to page 1
4. Click on page 2, it works
5. Click on page 3
6. You're back on page 1
7. Rince and repeat

**Expected behavior**
Should be able to browse all the pages

**Comment by julsemaan** [comment] 2019-07-25 15:22
This doesn't affect the latest devel but does affect the latest maintenance/9.0

**Comment by satkunas** [comment] 2019-07-29 16:47
Unable to reproduce on latest `maintenance/9.0`

**Comment by julsemaan** [comment] 2019-07-29 16:53
Seems to be browser specific where the issue is only with Firefox

**Comment by satkunas** [comment] 2019-11-21 19:29
No longer able to reproduce on FireFox v70.0. Closing.

**Closed as completed by satkunas** 2019-11-21 19:29 UTC
Labels: Type: Bug, Priority: High
