### ISSUE TITLE
Condition Is a Phone in radius audit log is not working properly

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1813] opened 2016-11-09 19:39 UTC
If you set the condition 'Is A Phone' with 'is/matches' as an operator and 'no/yes' as a value no results are coming back. Look on a request in 'details' they are wrote like that.

**Comment by jrouzierinverse** [comment] 2016-11-09 23:23
This is a duplicate of #1812

**Closed as completed** 2016-11-10 13:49 UTC
