### ISSUE TITLE
web admin: Date must be less than 2038-01-01 causes issue

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5063] opened 2020-01-16 12:19 UTC
**Describe the bug**
When we want to create a user without an expiration date, we set Registration Windows to `2038-01-01 00:00:00`. That's the default value for `admin` and `default` users in DB. However, this value is considered as invalid by frontend when you edit a user since 9.3.0.

**To Reproduce**
1. Try to edit any fields on `admin` user in web admin

=> You can't save due to restriction on end date of Registration Windows field.

**Expected behavior**
Allow to save 2038-01-01 00:00:00 as value or use another value to indicate a user that will never expire.

**Comment by julsemaan** [comment] 2020-01-16 16:11
IMO 2038-01-19 00:00:00 should be considered valid.

That was the limit we set on the server in the forms from what I recall so the frontend should be allowing it

**Comment by extrafu** [comment] 2020-01-16 16:14
Just imagine... @lzammit will be 50 at that date.

**Comment by julsemaan** [comment] 2020-01-16 16:17
And will probably have triplets by then

**Comment by extrafu** [comment] 2020-01-16 16:18
And 13 cats

**Comment by satkunas** [comment] 2020-01-17 18:12
We'll need to brainstorm on this. All the datepickers that I've seen have one issue or another. We're currently using flatpickr and it does not allow any dates to start with '0'. Thus the datetime component will need to be modified somehow to allow the user to manually choose 'unlimited'.

**Comment by jrouzierinverse** [comment] 2020-01-17 18:59
We would need to transition away from timestamps to Datetime or use 64-bit integers.
Since MariaDB timestamps are affected by the [Year 2038 problem](https://en.wikipedia.org/wiki/Year_2038_problem)

**Comment by julsemaan** [comment] 2020-01-17 19:43
Fully agree we should have a long term solution to this.

Nonetheless, we should have this working in the GUI for v9.x since that issue is currently a regression

**Comment by nqb** [comment] 2020-01-31 07:19
@satkunas, in order to fix this issue for 9.3.0 users, it's possible to have a workaround ?

**Comment by veedubbs** [comment] 2020-02-11 23:10
In previous PacketFence versions, we were able to have an empty unreg date.  That seems to no longer be the case.  In the 9.3.0 GUI when I clear the field, it automatically re-populates.

Is this what this thread is about?

**Comment by nqb** [comment] 2020-02-12 12:33
Hello @veedubbs,

I suppose you try that:
1. create a node with no unreg date
2. edit node and set an unreg date + save
3. try to remove unreg date: you can't

If you can confirm, I will open a separate issue because this one concerns users, not nodes. However, that's certainly related to the way frontend deal with dates.

**Comment by veedubbs** [comment] 2020-02-12 14:29
@nqb correct.

1. I can create a node with no unreg date.
2. I can edit that node and add an unreg date.
3. I cannot remove the unreg date and leave it blank (when I empty the field, it re-populates)

**Comment by satkunas** [comment] 2020-04-02 19:57
Issue was resolved in https://github.com/inverse-inc/packetfence/commit/2592ec737eedbe8a511b7f43e10412221fcda996#diff-76a5ebd610175a9566db01b6745a3d14

**Closed as completed** 2020-04-02 19:58 UTC
Labels: Type: Bug, Priority: Medium, Priority: High
