### ISSUE TITLE
Admin - nodes : Clicking next page when there is no results gives invalid values

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1532] opened 2016-06-07 21:45 UTC
When searching for : 
Node MAC - is - c8:bc:c8:8d:08:ff

I get the following (which is normal) : 
![image](https://cloud.githubusercontent.com/assets/3857942/15875729/717a59ba-2cd7-11e6-8741-ecbcebba4396.png)

Then, I click the next button and the search is ignored and replaced by a view of MACs that aren't part of the search:
![image](https://cloud.githubusercontent.com/assets/3857942/15875769/9d7511c2-2cd7-11e6-8ce9-8b8384aadbfd.png)

**Comment by jrouzierinverse** [comment] 2016-06-09 13:50
Duplicate of #1527

**Closed as completed by jrouzierinverse** 2016-06-09 13:50 UTC
Labels: Type: Bug
