### ISSUE TITLE
Exploding Logfiles (packetfence.log)

### ISSUE THREAD

**Issue by bebbet** [inverse-inc/packetfence#1755] opened 2016-10-11 23:15 UTC
My logfiles are really exploding with "Use of uninitialized value" is there some patch/toggle/switch available to silence this output, or a fix/workaround?

Example loglines (packetfence.log): 

Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 44.
 (pf::Connection::_attributesToString)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 94.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 97.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 100.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 103.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 493.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:22 httpd.aaa(2595) WARN: [mac:b8:6b:23:d8:1c:c0] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 496.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 44.
 (pf::Connection::_attributesToString)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 94.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 97.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 100.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 103.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 493.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 44.
 (pf::Connection::_attributesToString)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:9f:b0] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 496.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 44.
 (pf::Connection::_attributesToString)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 94.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 94.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 97.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 97.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 100.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 100.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 103.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm line 103.
 (pf::Connection::attributesToBackwardCompatible)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 493.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 493.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:a6:93] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 496.
 (pf::radius::_translateNasPortToIfIndex)
Oct 11 10:23:23 httpd.aaa(2595) WARN: [mac:50:e5:49:82:cb:63] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 496.
 (pf::radius::_translateNasPortToIfIndex)

**Comment by julsemaan** [comment] 2016-10-13 12:03
Seems that would be caused by an empty NAS-Port-Type in a RADIUS request.

Please provide the following:
- PacketFence version
- RADIUS request trace:
  - Go in 'Auditing', click on the 'Details', then go in the RADIUS tab of those details and paste the content of the 'RADIUS Request' field here

**Comment by bebbet** [comment] 2016-10-13 14:33
I've got MULTIPLE lines of these errors, but none (with this error) matching any auditlog entry. For the past 60 lines, i've got 2 in audit, which did succeed.

**Comment by julsemaan** [comment] 2016-10-14 12:54
Not sure I follow your point.

Are you able to extract the info I asked for the MAC `50:e5:49:82:cb:63`

Having them succeeding doesn't mean it won't output garbage in the log.

Also, please provide your PF version

**Comment by bebbet** [comment] 2016-10-18 07:49
No i'm not able to extract the info you asked for, there are no matching entries in the audit log, or in the database table for that matter. 

My pf version is 6.2.1. 

Happy to provide more info on request!

**Comment by julsemaan** [comment] 2016-10-18 11:37
Please attempt to install the following patch:

```
# cd /usr/local/pf && curl https://github.com/inverse-inc/packetfence/commit/650f14371649ba737fabe9f3322c3b4d93d1f83c.diff | patch -p1
# service packetfence restart
```

And let us know if that still happens

**Comment by bebbet** [comment] 2016-10-24 11:12
The issue persists, first day after vacation so the first day i could test.

**Comment by julsemaan** [comment] 2016-10-24 14:05
Try to apply the maintenance via:

```
# /usr/local/pf/addons/pf-maint.pl
# service packetfence restart
```

And try again

**Comment by bebbet** [comment] 2016-10-27 07:15
I've patched and monitored it for a while, because maybe after warm-up period the errors would decrease. 

However it seems to be exactly the same, or worse.

these errors persist: 

Use of uninitialized value in lc at /usr/local/pf/lib/pf/Connection.pm 
  line 44 sometimes, 97, 100, 103

Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm 
  line 493 and 496.

**Comment by slm4996** [comment] 2016-10-31 13:39
Same thing happening here. Fully patched via pf-maint.pl as of OCtober 31st, 9:30am EST.
Error log entry (also happens for line 493)

```
Oct 31 09:34:38 httpd.aaa(13983) WARN: [mac:88:51:fb:67:28:40] Use of uninitialized value $conn_type in bitwise and (&) at /usr/local/pf/lib/pf/radius.pm line 496.
 (pf::radius::_translateNasPortToIfIndex)
```

Audit log entry:

```
User-Name = "host/censcored"
NAS-IP-Address = 10.100.1.26
NAS-Port = 30
Service-Type = Framed-User
Framed-Protocol = PPP
Framed-MTU = 1480
State = 0xae98a6baafd9bc3341ffb703fb5114c4
Called-Station-Id = "30:8d:99:02:07:40"
Calling-Station-Id = "88:51:fb:67:28:40"
NAS-Identifier = "censcored-309-SW-1"
NAS-Port-Type = Ethernet
Tunnel-Type:0 = VLAN
Tunnel-Medium-Type:0 = IEEE-802
Tunnel-Private-Group-Id:0 = "302"
Event-Timestamp = "Oct 31 2016 09:04:23 EDT"
Connect-Info = "CONNECT Ethernet 100Mbps Full duplex"
EAP-Message = 0x024100061a03
NAS-Port-Id = "30"
FreeRADIUS-Proxied-To = 127.0.0.1
HP-Capability-Advert = 0x011a0000000b28
HP-Capability-Advert = 0x011a0000000b2e
HP-Capability-Advert = 0x011a0000000b30
HP-Capability-Advert = 0x011a0000000b3d
HP-Capability-Advert = 0x011a0000000b18
HP-Capability-Advert = 0x0138
HP-Capability-Advert = 0x013a
HP-Capability-Advert = 0x0140
HP-Capability-Advert = 0x0141
HP-Capability-Advert = 0x0151
MS-RAS-Vendor = 11
EAP-Type = MSCHAPv2
Realm = "null"
PacketFence-Domain = "censcored"
SQL-User-Name = "host/censcored"
```

**Comment by julsemaan** [comment] 2016-10-31 15:40
@jrouzierinverse I believe you did a few fixes around the undefined values of the connection type.

Any reason why they should still get garbage output using a v6 with latest maintenance patches ?

**Comment by julsemaan** [comment] 2016-12-20 18:38
@slm4996 

Are you still having this issue with the latest version (6.4)

If so we'll dig into it again

**Comment by slm4996** [comment] 2016-12-20 23:56
@julsemaan I'll double check our current patch level and logs then get back to you.

**Comment by slm4996** [comment] 2016-12-21 13:23
@julsemaan The latest repo package for CentOS release 6.8 still has the issue, however from 74c3eaac9067fbea53407fd84f99809c68fb675b applied via pf-maint.pl the logs are now clear of erroneous errors.

**Comment by julsemaan** [comment] 2016-12-21 13:53
If its fixed in the maintenance, then it will hit the future packages so thats good

**Closed as completed by julsemaan** 2016-12-21 13:53 UTC
Labels: Type: Bug
