### ISSUE TITLE
Inline Layer 2: Does not apply the unregdate

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6940] opened 2022-03-18 20:38 UTC
Once I register on the captive portal on the inline layer 2 network it register my device it does not assign any unregdate:

![aNgaP834h1HgEV0U](https://user-images.githubusercontent.com/5261214/159080033-b30521cc-c6da-47ef-a774-9316e4964800.jpg)

**Comment by nqb** [comment] 2022-03-21 08:50
Duplicate of #6925

**Closed as completed by nqb** 2022-03-21 08:50 UTC
Labels: Type: Bug, Priority: High, Priority: Critical
