### ISSUE TITLE
pfdns returns host entry for portal domain name

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5765] opened 2020-08-26 19:15 UTC
**Describe the bug**
If your portal domain name is `portal.zammitcorp.com` and you have a host entry for it, pfdns returns the host entry instead of the 66.70.255.147 address

**To Reproduce**
1. Set portal domain name to `portal.zammitcorp.com`
1. Add host entry:
```
1.2.3.4 portal.zammitcorp.com
```
1. Restart pfdns
1. Try to resolve portal.zammitcorp.com on pfdns, you'll get 1.2.3.4 instead of 66.70.255.147

**Expected behavior**
The portal domain name should not use the hosts entries to resolve

**Comment by julsemaan** [comment] 2020-08-26 19:24
The hosts middleware has precedence over the pfdns middleware as seen here:
https://github.com/inverse-inc/packetfence/blob/993a1d05b1e927206ad4151e13df9486e2ac0daa/go/coredns/core/dnsserver/zdirectives.go#L13-L43

And the hosts middleware is being used in pfdns.conf but I'm not sure why:
https://github.com/inverse-inc/packetfence/blob/993a1d05b1e927206ad4151e13df9486e2ac0daa/conf/pfdns.conf.example#L25-L29

The best solution would be to move the hosts directive under pfdns, above proxy or move pfdns above hosts. That way we can leave the hosts directive in pfdns.conf (although I'm not sure about why we'd use that)

**Comment by bbs2web** [comment] 2020-08-26 20:18
Was bitten by this today as well. I thought the go stuff needing to be compiled so I hashed out the 'hosts' section in pfdns.conf...

**Comment by fdurand** [comment] 2020-08-27 00:36
The hosts middleware has been added for inline mode, per example if the dns server used by the inline network is 8.8.8.8 and you want to be able resolve internal fqdn like internal smtp server.

The solution should be use this syntax:

```
hosts /usr/local/pf/conf/pf.hosts {
    fallthrough
}
```
So we use another file for that.
Also what is the reason to put the portal fqdn in the hosts file ?

**Comment by bbs2web** [comment] 2020-08-27 06:50
In our case the hostname of the system is packetfence.xxx.com, which is also the portal URL. Debian has a default approach of having a hosts entry matching the FQDN that resolves to 127.0.1.1, so the default pfdns.conf file resulted in all DNS queries in the registration network being directed at the correct IP except for the portal itself, which was resolving to 127.0.1.1 and obviously then not reachable.

Created a new empty file '/usr/local/pf/conf/pf.hosts' and updated pfdns.conf to add the filename after the 'hosts' definition as per fdurand's example and confirmed it everything to still be working as expected.

**Comment by julsemaan** [comment] 2020-08-27 11:06
> The hosts middleware has been added for inline mode, per example if the dns server used by the inline network is 8.8.8.8 and you want to be able resolve internal fqdn like internal smtp server.
> 
> The solution should be use this syntax:
> 
> ```
> hosts /usr/local/pf/conf/pf.hosts {
>     fallthrough
> }
> ```
> 
> So we use another file for that.
> Also what is the reason to put the portal fqdn in the hosts file ?

I know this is not common to do this (put the portal FQDN in the /etc/hosts) but when it does, its a pretty hard issue to troubleshoot and is not the behavior the user expects in a registration VLAN

For this case, moving the hosts middleware after pfdns should still allow you to do that so I think that will be our fix if you agree @fdurand

**Comment by fdurand** [comment] 2020-09-16 20:26
Agree

**Comment by julsemaan** [comment] 2020-09-18 15:26
This needs to go in the maintenance

**Comment by fdurand** [comment] 2020-09-18 15:37
Pushed to maintenance.

**Closed as completed by fdurand** 2020-09-18 15:37 UTC
Labels: Type: Bug, Priority: High
