### ISSUE TITLE
"Graphite encountered an unexpected error" for "NTLM authentication failures" graph only error

### ISSUE THREAD

**Issue by maria2027** [inverse-inc/packetfence#1978] opened 2017-01-24 03:03 UTC
Fresh install on Debian Jessie. 
All green, but in Dashboard -> "NTLM authentication failures" graph is missing.
On "View image" I get this error:

Graphite encountered an unexpected error while handling your request.

Please contact your site administrator if the problem persists.

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib/python2.7/dist-packages/graphite/render/views.py", line 110, in renderView
    seriesList = evaluateTarget(requestContext, target)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 10, in evaluateTarget
    result = evaluateTokens(requestContext, tokens)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 28, in evaluateTokens
    args = [evaluateTokens(requestContext, arg) for arg in tokens.call.args]
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 21, in evaluateTokens
    return evaluateTokens(requestContext, tokens.expression)
  File "/usr/lib/python2.7/dist-packages/graphite/render/evaluator.py", line 29, in evaluateTokens
    return func(requestContext, *args)
  File "/usr/lib/python2.7/dist-packages/graphite/render/functions.py", line 247, in diffSeries
    (seriesList,start,end,step) = normalize(seriesLists)
  File "/usr/lib/python2.7/dist-packages/graphite/render/functions.py", line 120, in normalize
    step = reduce(lcm,[s.step for s in seriesList])
TypeError: reduce() of empty sequence with no initial value

All other graphs are ok, only this one is returning error.

**Comment by tlaurion** [comment] 2017-01-25 21:53
`TypeError: reduce() of empty sequence with no initial value`
Only happens when there is no data. It resolves itself when NTLM auth happens.

**Comment by maria2027** [comment] 2017-01-25 22:21
On all other graphs without data I see "No data" png in reports page.
Only this particular graph is showing error. Is there any patch I can apply in order to get the "No data" png instead of this ugly error?

Thanks,
M.

**Comment by tlaurion** [comment] 2017-03-31 20:35
@maria2027 Sorry I closed this ticket without seeing you message. Is this problem still happening to you? Which version of PacketFence are you using?

**Comment by louismunro** [comment] 2017-04-02 16:08
It's not a bug.
It will out when you actually have data.

To be clear, this may be be fixed in a later graphite release, but since we depend on upstream packagers for that at the moment we can't fix it ourselves.

Someday we'll package graphite on our own.

**Closed as completed by louismunro** 2017-04-02 16:08 UTC

**Comment by louismunro** [comment] 2017-04-02 16:09
@tlaurion please don't assign issues to me without asking first.

**Comment by maria2027** [comment] 2017-04-03 09:26
"Unexpected error" is something we know what it is. There is no "Unexpected error" on ANY of other graphs, only on this one.
However, you are THE DEVELOPER, you know better, don't you ? :-)Please implement the "Unexpected error" on ALL graphs, because in this case, ALL other graphs have a bug :-)))))

**Comment by maria2027** [comment] 2017-04-03 09:45
Btw, I am using the last version of pf updated daily. 
The problem is clear for any developer with more than 5 seconds of programming experience.

However, since not any user will ever have data in NTLM table, things are clear.

If this is  "not a bug" , @louismunro, please, please implement the same code on ALL other graphs not having the "Unexpected error"  and "contact administrator" features implemented. 
Should I report as "bugs" all correctly treated exceptions in pf code?
Cause I can write a script to do that... :-)))

No, I am joking, we are all here to learn how to write code in a safe way, especially when we learn coding from youtube...

**Comment by louismunro** [comment] 2017-04-03 13:41
Feel free to submit a PR then.
Note that it probably should be sent to the graphite developers, since the original error is in that code.
