### ISSUE TITLE
PF8 Fingerbank error

### ISSUE THREAD

**Issue by TomInverse** [inverse-inc/packetfence#3046] opened 2018-03-27 14:10 UTC
Found in journalctl:
Mar 27 09:44:26 tom-sanitarium /usr/local/fingerbank/collector/fingerbank-collector[14622]: t=2018-03-27T09:44:26-0400 lvl=eror msg="Error while handling packet: illegal base64 data at input byte 0" pid=14622
Mar 27 09:44:26 tom-sanitarium /usr/local/fingerbank/collector/fingerbank-collector[14622]: t=2018-03-27T09:44:26-0400 lvl=eror msg="Error while handling packet: illegal base64 data at input byte 1" pid=14622

**Comment by julsemaan** [comment] 2018-03-28 21:29
This is actually caused by all of our collectors sharing the same L2 network with different encryption keys (Fingerbank API key)

I'm investigating how to adjust the code

**Comment by julsemaan** [comment] 2018-03-28 21:36
fixed by c2e3502b12457a541306f473f0c2070ccda2296a in the collector repo.

Will get a new package ready in devel for tomorrow

**Closed as completed by julsemaan** 2018-03-28 21:36 UTC
Labels: Type: Bug, Priority: High
