### ISSUE TITLE
Admin roles: underscores in name cause issue

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4855] opened 2019-10-14 10:00 UTC
When I assigned an admin role that contains underscores in its name to a user, web browser freezes during log in of user (tested on two different browsers).

**To Reproduce**
* Create an admin role called `node_manager_role`:
```
[node_manager_role]
actions=NODES_CREATE
allowed_roles=
allowed_node_roles=role1
description=Manager of nodes with role1
allowed_access_levels=
allowed_actions=
```
* Create a user `foobar` with access level set as `node_manager_role`
* Log in as `foobar` user

=> Web browser freezes during log in.

**Expected behavior**
User should be able to log in.

**Additional context**
In logs, I see following message:
`httpd.admin(8426) ERROR: [mac:unknown] One of the following roles are not defined properly 'node_manager_role' (pfappserver::PacketFence::Controller::Admin::login)`

**Comment by jrouzierinverse** [comment] 2019-10-18 10:13
The problem is you need at least one of these admin roles to login through the old admin.

SERVICES_READ REPORTS_READ USERS_READ NODES_READ CONFIGURATION_MAIN_READ
CONNECTION_PROFILES_READ PROVISIONING_READ ADMIN_ROLES_READ INTERFACES_READ
SWITCHES_READ FLOATING_DEVICES_READ USERS_ROLES_READ USERS_SOURCES_READ
SECURITY_EVENTS_READ FINGERPRINTS_READ MAC_READ
FINGERBANK_READ FIREWALL_SSO_READ REALM_READ DOMAIN_READ SCAN_READ
WMI_READ PKI_PROVIDER_READ WRIX_READ FILTERS_READ PORTAL_MODULE_READ
USERS_READ_SPONSORED AUDITING_READ SELF_SERVICE_READ

I am closing this as it is working as designed.

**Closed as completed by jrouzierinverse** 2019-10-18 10:13 UTC
Labels: Type: Bug, Priority: Medium
