### ISSUE TITLE
Debian 9 support?

### ISSUE THREAD

**Issue by blackyzero** [inverse-inc/packetfence#2460] opened 2017-07-05 16:31 UTC
Dear everyone,

Does current release support Debian 9?

Thank you.

**Comment by fdurand** [comment] 2017-07-05 16:32
Not yet, i have issue with the wmi feature.

**Comment by dwlfrth** [comment] 2017-07-05 18:01
This will be closed as it does not represent a development issue with PacketFence.
Thanks

**Comment by nqb** [comment] 2018-03-06 12:05
Debian 9 has been released in June 2017. It's time to provide a Debian package for Stretch

> i have issue with the wmi feature

What kind of issue ? Maybe I can help.

**Comment by fdurand** [comment] 2018-03-07 00:49
Agree, it's time but i miss time.
The issue is that it's complicate to build the perl-wmi lib to support wmi on Strech.
What i tried to do is to use Inline::Python in order to use python impacket in order to do be able to do a WMI scan. The issue i got is that apache seg faulted on Strech (not on Jessie).
So i decided to use another way and use golang to embed python and use impacket.
The POC works but i missed time to finish it (https://github.com/inverse-inc/packetfence/compare/feature/pfwmi?expand=1).
So if you are interested to check the code and maybe finish it, it will be a pleasure for me to finally support Debian Strech.

**Comment by victorhooi** [comment] 2018-08-22 21:55
@fdurand Did you get any luck getting PacketFence to work on Debian 9 (Stretch) again?

Is there any chance that WMI can be made optional, so that PacketFence still installs on Debian?

**Comment by Szeraax** [comment] 2018-08-23 14:59
Wow, I feel the same as @victorhooi. I'm not willing to install jessie for a new production nac. I'm going to try installing on Stretch here in about 10 minutes and see if I can get it to work. If not, i'll just have to use the other distro that shall not be named.

**Comment by Szeraax** [comment] 2018-08-23 15:23
Darn, can't get it to work. Guess I'm going to CentOS. still can't install WMI-Client.

**Comment by victorhooi** [comment] 2018-09-14 11:06
Is it possible to re-open this issue please?

PacketFence still doesn't work on Debian 9 - and Debian 8 will eventually go EOL.

And the provided VM images only work on VMware, not KVM.

(I assume if we can get working modern Debian support - Ubuntu support may come for free as well).

**Comment by julsemaan** [comment] 2018-09-14 12:33
Resources for adding full Debian 9 support are limited in our team and while the team has provided support for it for many years, the de-facto distribution used by Inverse is CentOS so that is where the efforts go which means Debian definitely receives less love.

Bottom line is, unless you absolutely have to install Debian, stick with CentOS
(this last opinion is personal)

**Comment by zerwes** [comment] 2018-11-24 04:57
sad to hear this ...
I clearly understand the problem of limited dev resources and budgeting these but creating a de-facto standard in the open source context by limiting the support to a single distro is  hard to accept.
Our complete linux ecosystem is based on debian (and a few ubuntu setups), so using a different base distro just for one system is in fact no option.

**Comment by extrafu** [comment] 2018-11-24 11:55
Debian 9 might be supported in v8.3 without WMI support.

Debian 9 will most likely be supported with WMI support as we'll remove some dependencies we have on Samba 4 that cause issues on Debian 9.

**Comment by rlsit** [comment] 2018-11-26 10:09
Good news!
Is there a time schedule for this available?
We are planing to integrate packetfence into our IT infrastructure ... and for the linux part we use debian (all other tools like ansible etc. are geared on this distro).

**Comment by zerwes** [comment] 2018-12-07 04:45
Happy to read that debian has not been forgotten completely :+1: Thx for this!
would it be possible to reopen this issue until it is fixed? If there are plans to support debian 9 in the future closing the issue w/ resolution of wont't fix seems inadequate.

**Comment by nqb** [comment] 2018-12-07 06:33
We are working on it ! Stay tuned.

**Comment by rlsit** [comment] 2018-12-07 10:15
:+1: great && thx

**Comment by victorhooi** [comment] 2019-02-03 14:18
Just wondering - is there a plan or roadmap as to which specific future version of PacketFence might support Debian again? (With or without WMI support).

**Comment by extrafu** [comment] 2019-02-04 02:05
v9.

**Closed as completed** 2019-03-14 17:40 UTC
