### ISSUE TITLE
Unable to delete roles

### ISSUE THREAD

**Issue by rcmcdonald91** [inverse-inc/packetfence#3940] opened 2019-01-16 20:20 UTC
There is no way to delete roles from the web GUI in 8.3.0

**Comment by julsemaan** [comment] 2019-01-16 20:57
This is intended. Any prior way to delete a role was an issue.

You shouldn't be deleting roles in PacketFence. We need to eventually address this but its not something that is possible now.

**Comment by nqb** [comment] 2019-03-22 12:40
@julsemaan,

We need at least to document how to delete properly a role in PacketFence's docs.

**Comment by julsemaan** [comment] 2019-03-22 12:44
Right now we shouldn't be deleting roles. This is something that should not be done so we shouldn't document how to do it.

When we want to be able to do this, we should do it properly by implementing it in the code, not providing all the steps to go clean it up in the config + DB which would be error prone IMO.

Might as well do it right in our implementation instead of providing the guidelines

**Comment by nqb** [comment] 2019-03-22 12:48
Steps I have in mind if we want to delete role "test":
* unassign role "test" from all nodes
* update all authentication sources where role "test" is assigned
* update all connection profiles or portal modules where role "test" is in use
* remove role "test" in $CONF/roles.conf
* remove role "test" in $CONF/switches.conf

Then do a `pfcmd configreload hard`. Last two steps need to be done on each cluster member in a cluster environment.

@julsemaan, tell me if I'm wrong.

**Comment by extrafu** [comment] 2019-03-22 12:58
The problem is that we cannot simply "unassign" a role for nodes - you have to transfer all nodes to a new role (or new roles), or unregister all of them.

**Comment by cgx** [comment] 2019-03-22 13:52
One possible short-term option: let the user delete a role only if no nodes are assigned to it.

**Comment by nqb** [comment] 2019-03-22 13:52
Not agree @extrafu. On a node registered with a role "guest", I can simply remove its role and set it to "No role".

**Comment by extrafu** [comment] 2019-03-22 13:54
Yes and what happens then when the device is registered and no role is assigned to it and it connects using MAC authentication? Shit will hit the fan and it'll get ugly.

**Comment by julsemaan** [comment] 2019-03-22 14:02
@extrafu's arguments are the reason why we need to have this done in a clean way

Like a wizard that guides you through the deletion, asks you what to do with the nodes associated to the role (unreg or change role), asks you what to do with auth rules with this role (delete them or change to another role). Then with that info in hand, it goes and modifies the config + DB and does the housekeeping.

**Comment by julsemaan** [comment] 2019-03-22 14:02
![image](https://user-images.githubusercontent.com/3857942/54828007-a12fb680-4c89-11e9-82f1-bba3403c160a.png)

**Comment by extrafu** [comment] 2019-03-22 14:03
@julsemaan Is that @lzammit ?

**Comment by julsemaan** [comment] 2019-03-22 15:18
Also, to add to the list of housekeeping @lzammit's cousin will have to do:
- provisioners
- scan engines
- device registration
- vlan filters
- radius filters
- firewall SSO
- billing tiers

and I'm probably forgetting some

**Comment by nqb** [comment] 2020-04-09 11:15
> One possible short-term option: let the user delete a role only if no nodes are assigned to it.

This idea sounds good from my point of view, I'm pushing to v10.1.

**Comment by cdcrawford** [comment] 2020-06-22 12:22
So, I take it this will be pushed to v10.2 as it does not look like it was included in the bug fixes, new an changed features report for 10.1.0.

Release Notes:
https://github.com/inverse-inc/packetfence/blob/devel/NEWS.asciidoc

GIT Diff:
https://github.com/inverse-inc/packetfence/compare/v10.0.0...v10.1.0

This would be a game changer for us, we have a number of roles that were carried forward from our old testing installation that are no longer used, I'd love to remove them.

**Closed as completed** 2020-09-18 15:44 UTC
Labels: Type: Feature / Enhancement, Priority: Low
