### ISSUE TITLE
Embedded Documentation links are broken.

### ISSUE THREAD

**Issue by jrouzierinverse** [inverse-inc/packetfence#7504] opened 2023-02-07 01:50 UTC
The embedded documentation just opens the help but does not display documentation related to the link clicked.

**Comment by julsemaan** [comment] 2023-02-07 12:53
Looks like a dupe of #7305

**Comment by satkunas** [comment] 2023-02-07 16:43
Possibly related to #7503. We will bump nodejs version to 14.x to have consistency with my build environment before revisiting.

**Closed as completed** 2023-02-16 17:24 UTC
Labels: Type: Bug
