### ISSUE TITLE
WebAdmin: Node Import

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#6223] opened 2021-03-24 15:00 UTC
**Describe the bug**
Unable to close the file when you click on the cross

![image](https://user-images.githubusercontent.com/1553962/112332494-28a4cb80-8c90-11eb-9b54-d4a5a0a1087f.png)

**Comment by nqb** [comment] 2021-03-24 15:06
Duplicate of #6206

**Closed as completed by nqb** 2021-03-24 15:06 UTC
Labels: Type: Bug
