### ISSUE TITLE
Send rate-limit values via radius for Ruckus APs

### ISSUE THREAD

**Issue by garci66** [inverse-inc/packetfence#6595] opened 2021-09-22 15:46 UTC
**Is your feature request related to a problem? Please describe.**
Ruckus WLAN controllers support the following RADIUS attributes: `WISPr-Bandwidth-Max-Down=20000` and `WISPr-Bandwidth-Max-Up=128000` which allow a per-user rate limit. While today this is achievable using ROLES, the total number of ROLES available in a Smartzone controller can be quite limited (64 total). If the controller is used in a multi-tenant scenario, this can be quite limiting. Also, specifying new upload/download rates means creating a new role in the controller while it could be done directly in PF without needs to configure additional parameters in the controller

**Describe the solution you'd like**
Ideally, we could have a flag in the SZ controller where the "Role-by-role" section of the configuration gets interpreted and instead of using the `Ruckus-User-Groups` RADIUS attribute, the `WISPr-Bandwidth-Max-Down` and `WISPr-Bandwidth-Max-Up` could be populated instead.  For example, if we name the flag something like "Use WISPr Bandwitdh attributes", then if the "Role-by-Role" has a format similar to `20000-10000` for example, then instead of sending the `Ruckus-User-Groups`  attribute, we would send the  `WISPr-Bandwidth-Max-Down=20000` and `WISPr-Bandwidth-Max-Up=10000` instead.

I can help build the code but im not 100% sure how to add an additional "knob" / "flag"  in the new UI for a specific "switch"

**Describe alternatives you've considered**
Alternatively, we could avoid the "flag" entirely and just test that "role-by-role" value. If it matches the `\d+-\d+` regexp, use the WISPR attributes. Otherwise, use the User-groups one. But this could break some existing users

**Additional context**
BTW, this should work on both SmartZone and recent (9.0 or newer) ZoneDirector controllers, so pretty much all devices. Not 100% sure about Unleashed. I believe that since this attributes are not Ruckus specific, they probably can be used also on Aruba / etc.

**Comment by julsemaan** [comment] 2021-09-22 16:27
I'll mark this as a dupe of https://github.com/inverse-inc/packetfence/issues/5905 since this issue here is a more opinionated version of #5905

In the meanwhile you can use the RADIUS filter engine to accomplish this by creating rules that match on the role and add the RADIUS attributes to your reply

**Closed as completed by julsemaan** 2021-09-22 16:27 UTC
Labels: Type: Feature / Enhancement

**Comment by garci66** [comment] 2021-09-22 17:34
Thanks @julsemaan, indeed, #5905 seems much more extensive / complete. In my case, I focused on Ruckus since thats most of our installed based, but the other solution would benefit the project much more.

I'll take a look at the radius filter in the meantime!
