### ISSUE TITLE
Sort for Online/Offline in nodelist doesn't work

### ISSUE THREAD

**Issue by Venice-89** [inverse-inc/packetfence#1687] opened 2016-09-02 09:54 UTC
Hi,

if you try to sort the node list via clicking on online/offline, the list is empty after that.

Greetings
Tobias

**Comment by julsemaan** [comment] 2016-09-30 17:39
Hi Tobias,

Thanks for the report.

This is a duplicate of #1714 

Please refer to it for the fix related to this issue.

Thanks

**Closed as completed by julsemaan** 2016-09-30 17:39 UTC
