### ISSUE TITLE
Admin - Switch Templates missing RADIUS value

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5424] opened 2020-05-08 20:45 UTC
Some switch templates are not displaying the RADIUS value.

![Screenshot_20200508_164234](https://user-images.githubusercontent.com/3904468/81447714-26568300-914b-11ea-9909-4e873221f615.png)

In this example `Tunnel-Private-Group-Id` is missing the value `$vlan`.

![Screenshot_20200508_164434](https://user-images.githubusercontent.com/3904468/81447751-353d3580-914b-11ea-92f9-817e40d28fcf.png)

**Comment by satkunas** [comment] 2020-05-08 20:49
Issue appears to be same as https://github.com/inverse-inc/packetfence/issues/5281

**Comment by satkunas** [comment] 2020-05-08 20:50
@nqb can you have a look at this?

**Comment by heat391** [comment] 2020-05-14 11:32
I have discovered a similar issue when creating a switch template via CLI as outlined the in the Developer's Guide and using Vendor Specific Attributes; likely related to the same issue:

![Vendor Attributes](https://user-images.githubusercontent.com/63456298/81929434-009b0500-95b5-11ea-8a34-4b21e1bab5f9.PNG)

**Comment by nqb** [comment] 2020-05-14 11:54
@satkunas, in your screenshot, I noticed that `ID` is used in place of `Id`. Which switch template did you try to display ?

@heat391, could you try to create your switch template directly from GUI in place of using CLI ?

**Comment by heat391** [comment] 2020-05-14 12:03
When created in the GUI I the field does show up.  However, the attribute is not passed to the switch... I don't know if the not passing the attribute is part of this issue or a wholly different issue...
Screenshots below:

![image](https://user-images.githubusercontent.com/63456298/81932041-11e61080-95b9-11ea-92d0-83e626ceb034.png)

![image](https://user-images.githubusercontent.com/63456298/81932157-540f5200-95b9-11ea-84ff-a3c280c6a4e4.png)

**Comment by heat391** [comment] 2020-05-18 12:52
Do I need to create a new issue regarding the attributes not being sent to the switch, or do you feel it is part of this issue?

**Comment by nqb** [comment] 2020-05-18 13:05
Hello @heat391,

Please create a dedicated issue with steps to reproduce and PF version used.

**Comment by nqb** [comment] 2020-05-19 10:10
I'm closing this one because `Tunnel-Private-Group-ID` should not be used and it can't occur if you use GUI.

**Closed as completed by nqb** 2020-05-19 10:10 UTC
Labels: Type: Bug, Priority: High
