### ISSUE TITLE
RADIUS_Audit_log: Audit tab does not show entries properly

### ISSUE THREAD

**Issue by atran-inverse** [inverse-inc/packetfence#3000] opened 2018-03-09 22:22 UTC
In devel, the Auditing tab only shows one entry:
![image](https://user-images.githubusercontent.com/36165527/37232757-5426d9f8-23be-11e8-98a7-5b89f4ed13d2.png)

There should be more since I was doing tests.

**Comment by julsemaan** [comment] 2018-03-12 12:37
This could be caused by the fact that entries aren't always assigned a tenant ID.

On my testing environment, I have a bunch of entries that have the tenant ID 0 and they aren't displayed in that view

**Comment by jrouzierinverse** [comment] 2018-03-19 16:34
As @julsemaan explained this is expected behavior.
We should close this issue as it would be addressed in the newer admin.

**Comment by extrafu** [comment] 2018-04-04 18:10
@julsemaan Should be closed?

**Comment by julsemaan** [comment] 2018-04-04 19:02
yep

**Closed as completed by julsemaan** 2018-04-04 19:02 UTC
Labels: Type: Bug, Priority: Medium
