### ISSUE TITLE
Click on switch ip in node info doesn't work. (Admin Gui)

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#1143] opened 2016-01-13 16:39 UTC

**Comment by julsemaan** [comment] 2016-01-13 16:59
What do you mean doesn't work ?

From what I recall that never opened anything

Issue #857 ?

**Comment by jrouzierinverse** [comment] 2016-01-20 20:37
This seem like it should be a feature not a bug.
Should we just close this issue or #857

**Closed as completed** 2016-01-20 22:26 UTC
Labels: Type: Bug
