### ISSUE TITLE
v9-gui - Firewall sso page just spinning

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#4400] opened 2019-05-08 19:04 UTC
![image](https://user-images.githubusercontent.com/1553962/57400946-a0ec6b80-71a2-11e9-91bd-546ea00d4f2b.png)

**Comment by julsemaan** [comment] 2019-05-08 19:38
Loads on my end, errors in the JS console?

**Comment by fdurand** [comment] 2019-05-08 19:39
nop

**Comment by satkunas** [comment] 2019-05-08 19:51
Not able to reproduce. Closing.

**Comment by satkunas** [comment] 2019-05-08 20:03
Moved to #4404

**Closed as completed by satkunas** 2019-05-08 20:03 UTC
