### ISSUE TITLE
httpd.aaa logging config is taken from httpd.webservices

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#2350] opened 2017-05-25 20:09 UTC
conf/log.conf.d/httpd.aaa.conf is ignored by the httpd.aaa service and takes whatever is in conf/log.conf.d/httpd.webservices.conf

Easiest way to replicate is to change the log level in the httpd.aaa.conf file and then see that it will still log in info

**Comment by dwlfrth** [comment] 2017-05-30 18:43
Status on this ?
ETA ?

**Comment by dwlfrth** [comment] 2017-05-31 14:21
@jrouzierinverse PLEASE ADVISE

**Comment by jrouzierinverse** [comment] 2017-05-31 15:26
Should be taken care of by 2d8877a6a009af699a3d502116c3fe1a105f7203

**Comment by dwlfrth** [comment] 2017-05-31 15:35
So we can close it ?
@julsemaan, @louismunro, can you make sure it is fixed ?

**Comment by julsemaan** [comment] 2017-06-01 13:37
Will attempt to test it out today

**Comment by louismunro** [comment] 2017-06-01 15:30
Not working for me at the moment.
Looking into it, but it does not seem to have worked it's magic.

**Comment by louismunro** [comment] 2017-06-01 15:37
Definitely not fixed in latest build.

**Comment by jrouzierinverse** [comment] 2017-06-01 16:19
After doing some more tests the description of the issue is incorrect.
httpd.aaa and  httpd.webservices takes it config values from conf/log.conf.
Not conf/log.conf.d/httpd.aaa.conf or conf/log.conf.d/httpd.webservices.conf.
Let me check why this is the case.

**Comment by julsemaan** [comment] 2017-06-01 16:33
@jrouzierinverse, when the issue was opened it was accurate, maybe recent changes have modified that

**Comment by jrouzierinverse** [comment] 2017-06-01 17:09
@julsemaan Did the also change the logging level of conf/log.conf.d/httpd.webservices.conf to see if it affects httpd.aaa

**Comment by julsemaan** [comment] 2017-06-01 17:15
![image](https://cloud.githubusercontent.com/assets/3857942/26691760/4febbdba-46cc-11e7-9fd0-9319a964f1eb.png)

**Comment by jrouzierinverse** [comment] 2017-06-01 17:20
How did you know that it was taking from conf/log.conf.d/httpd.webservices.conf and not somewhere else?

**Comment by jrouzierinverse** [comment] 2017-06-01 17:24
Fixed by 0d92871141850dbf9e323c5b38b3eb3be5488dcf

**Comment by dwlfrth** [comment] 2017-06-01 17:26
Should this be considered as a "+1" milestone ?

**Comment by louismunro** [comment] 2017-06-01 17:27
It does worry me a little to make that change minutes before releasing...

**Comment by dwlfrth** [comment] 2017-06-01 17:29
The require file is only used for importing libs (AFAIK) and also initiate the logger.
Having it "required" first rather than "post" only make the logger initialize sooner.
(From what I can understand). So I don't think there is too much to worry about...
@jrouzierinverse could advise ?

**Comment by jrouzierinverse** [comment] 2017-06-01 17:36
The changes will not take place since the .example file was changed not the config template.

So if we would have add an additional step to copy the .example file to config template.

So yes if you are willing to do the additional step no if you are not.

**Comment by louismunro** [comment] 2017-06-01 17:43
That step is actually done in the packaging.
As things stand now, this change will affect any 7.1.0 install.

**Comment by jrouzierinverse** [comment] 2017-06-01 17:45
The only potential issue is that STDERR stream is not available during the restart phase so any errors will not show up in the error_log.
However if there is an error causing it not to load it will apache will not start.

You can read more here
https://perl.apache.org/docs/2.0/user/config/config.html#C_PerlConfigRequire_

> One of the reasons for avoding using the PerlConfigRequire directive, is that the STDERR stream is not available during the restart phase, therefore the errors will be not reported. It is not a bug in mod_perl but an Apache limitation. Use PerlPostConfigRequire if you can, and there you have the STDERR stream sent to the error_log file (by default).

**Closed as completed by jrouzierinverse** 2017-06-01 17:45 UTC
Labels: Type: Bug

**Comment by louismunro** [comment] 2017-06-01 17:50
Ok, release the kraken then.

**Comment by jrouzierinverse** [comment] 2017-06-01 17:59
Let Liam Neeson say it
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/7SqC_m3yUDU/1.jpg)](https://www.youtube.com/watch?v=7SqC_m3yUDU)

**Comment by dwlfrth** [comment] 2017-06-01 18:00
And if the bug comes back,
https://www.youtube.com/watch?v=mmLRTVYgEq4
