### ISSUE TITLE
v9-gui: several issues with connection profiles

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4512] opened 2019-05-15 09:12 UTC
Several issues when creating a new connection profile from **new** GUI:

- [x] All dropdown lists are empty:

### Root Portal module
![Screenshot from 2019-05-15 11-07-00](https://user-images.githubusercontent.com/10830260/57763426-a34e4880-7701-11e9-8834-caa4b5af5141.png)

### Filters
![Screenshot from 2019-05-15 11-54-17](https://user-images.githubusercontent.com/10830260/57766745-338f8c00-7708-11e9-9b66-92d6ac084a32.png)

### Device registration
![Screenshot from 2019-05-15 11-54-36](https://user-images.githubusercontent.com/10830260/57766764-4013e480-7708-11e9-8b36-cd651576e14d.png)

**Comment by nqb** [comment] 2019-05-15 10:10
Error message in `packetfence.log`:

```
May 15 10:07:37 49f68a00e21e packetfence: ERROR pfperl-api(5519): Can't use string ("10m") as a HASH ref while "strict refs" in use at /usr/local/pf/lib/pf/UnifiedApi/Controller/Config.pm line 765.      │
 (Mojolicious::Plugin::DefaultHelpers::_development) 
```

**Comment by julsemaan** [comment] 2019-05-15 12:04
seems to be caused by 82adccc2c6681635ed94c529d582b1effe0d8b38

**Comment by nqb** [comment] 2019-05-15 13:38
I got same error message when I go to: https://IP_MGMT:1443/admin/alt#/configuration/security_event/1300005

**Comment by jrouzierinverse** [comment] 2019-05-15 14:19
Fixed by 30eac14f1469c69f44c7199e2ce258fb99d12496 and 3b0ab86f187aa4cd53abf6665626d0bfe129fe22

**Comment by nqb** [comment] 2019-05-15 14:41
Commits mentioned fixed this issue. 

**However**, I create two new connection profiles (one from new GUI and another from old GUI). Both have `locale=` in `profiles.conf` with `lang=en_US` for default connection profile.

@jrouzierinverse, could you check why ?

**Comment by jrouzierinverse** [comment] 2019-05-15 14:44
This is not a new behavior

**Comment by extrafu** [comment] 2019-05-15 14:46
If that's the case, we push this to v9.0.1 and we'll advise.

**Comment by nqb** [comment] 2019-05-15 14:56
@jrouzierinverse: are you sure ? For me, new connection profiles inherits values from default connection profile (`locale` setting included). I'm sure @julsemaan can confirm.

**Comment by jrouzierinverse** [comment] 2019-05-15 15:09
You can test this by installing 8.3.0 and see for yourself.

**Comment by nqb** [comment] 2019-05-16 05:33
@jrouzierinverse is right.

**Comment by nqb** [comment] 2019-05-16 05:34
This looks like a strange behavior from my point of view. New connection profiles should inherits from default connection profile for `locale` too.

**Comment by jrouzierinverse** [comment] 2019-05-16 14:17
I will move this to 9.1 as I do not what to change the behavior on a minor version.

**Closed as completed** 2020-04-01 08:10 UTC
Labels: Type: Bug, Priority: Critical
