### ISSUE TITLE
Issues with local users

### ISSUE THREAD

**Issue by veedubbs** [inverse-inc/packetfence#5509] opened 2020-06-02 19:33 UTC
Running PF V10.0.1.

**Describe the bug**
Three issues with local PF accounts.

1)  Creating a user does not require an email address, but when you search for an existing user (that doesn't have an email), it states one is required.

2)  The 'Unregistration date' action does not provide a pop-up calendar.

3)  You can create a user without any Actions, but if you attempt to add Actions later, you can configure them, but you can't save (Save button is grayed out).

**To Reproduce**
1. Go to 'Users'
2a. Click on 'Create' AND/OR
2b. Click on 'Search'

**Screenshots**
![image](https://user-images.githubusercontent.com/382007/83560424-d9609500-a4db-11ea-8b54-30b63236cd80.png)

![image](https://user-images.githubusercontent.com/382007/83560454-e9787480-a4db-11ea-9176-47bbe7750a0a.png)

**Expected behavior**
1) Email should be required during user creation.

2) Calendar should pop-up when setting Unregistration date action

3) Actions should either be required during user creation OR Save button should work when applying Actions to existing users.

**Desktop (please complete the following information):**
 - OS: Windows 10, build 1909
 - Browser: Chrome/Firefox
 - Version: 83/77

**Comment by julsemaan** [comment] 2020-06-04 11:42
@satkunas, can you look at the 3 issues here and check out the frontend part. Let us know if some stuff needs to be changed in the backend too

**Comment by satkunas** [comment] 2020-06-04 12:23
> 1. Email should be required during user creation.

A fix will be pushed shortly for this.

> 2. Calendar should pop-up when setting Unregistration date action

This will be fixed in another PR that I am currently working on (Not yet available).

> 3. Actions should either be required during user creation OR Save button should work when applying Actions to existing users.

@jrouzierinverse `actions` in PATCH payload is present but appears to be ignored.

@veedubbs the save button is only greyed out when there is a validation error in the form. If this is occurring and there are no red tabs or input elements visible then I'll need more information in order to replicate it.

**Comment by veedubbs** [comment] 2020-06-04 14:21
@satkunas Here is the user without any actions and the Save button greyed out:

![image](https://user-images.githubusercontent.com/382007/83768472-71798e00-a644-11ea-8097-2b5d28fc4e35.png)


Here is the user with a validation error in the form and Save button greyed out:

![image](https://user-images.githubusercontent.com/382007/83768555-8e15c600-a644-11ea-8983-9042e675d691.png)


Here is the use with no validation error and the Save button still greyed out:

![image](https://user-images.githubusercontent.com/382007/83768737-c6b59f80-a644-11ea-9776-cc89529fccc9.png)

**Comment by satkunas** [comment] 2020-06-05 17:46
@veedubbs I'm unable to reproduce. It appears there's a validation error on a hidden field, so there's no visual indication except for the disabled Save button.

You can get the entire form - inc. hidden fields - by running the following Javascript command in the browsers developer console. Remove any sensitive information from the output before posting.


```Javascript
JSON.stringify(document.getElementsByTagName('a')[0].__vue__.$store.state.formUserView.$form, null, 2);
```

**Comment by nqb** [comment] 2020-06-08 05:26
My 2 cents: the Save button can be greyed if you had errors in other tab than "Actions".

**Comment by satkunas** [comment] 2020-06-08 10:57
@nqb that tab will be colored red if it contains an error.

**Comment by veedubbs** [comment] 2020-06-08 14:00
@satkunas does this show you what you need?

![image](https://user-images.githubusercontent.com/382007/84039124-68e7c700-a966-11ea-97a1-c30efa7b910b.png)

**Comment by satkunas** [comment] 2020-06-15 14:15
@veedubbs related changes were made in https://github.com/inverse-inc/packetfence/issues/5564

Please let us know if these fixes also resolved your issues.

**Comment by veedubbs** [comment] 2020-06-17 14:54
@satkunas it looks like email address is now a required field when creating a local user. 

But trying to add actions to an existing user still has the Save button greyed out and not clickable:

![image](https://user-images.githubusercontent.com/382007/84913760-7c8ae000-b080-11ea-904e-670633c1ea7c.png)

**Comment by julsemaan** [comment] 2020-06-18 11:51
@satkunas, I think we should make the email mandatory during creation as it is but when editing a user, if there isn't an email, let's not require it anymore

**Closed as completed** 2021-02-03 22:27 UTC
Labels: Type: Bug, Priority: Medium
