### ISSUE TITLE
Unable to install from Debian package: Modification of a read-only value attempted errors in httpd.admin.error log

### ISSUE THREAD

**Issue by kzoli** [inverse-inc/packetfence#1855] opened 2016-11-21 15:29 UTC
[Sorry about my terrible English]
Debian Jessie environment (real box), fresh install, fully upgraded:
Linux packetfence 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux
PF packages from Inverse:
deb http://inverse.ca/downloads/PacketFence/debian jessie jessie
apt-get install packetfence
1. From /var/apt/term.log:
Failed to restart packetfence-config.service: Unit packetfence-redis-cache.service is masked.
redis_cache.conf seem to be missing(?), then:
touch /usr/local/pf/conf/redis_cache.conf
chown pf:pf /usr/local/pf/conf/redis_cache.conf
chmod 664 /usr/local/pf/conf/redis_cache.conf
apt-get install packetfence # again
2. From /var/apt/term.log:
Job for packetfence@httpd.admin.service failed. See 'systemctl status packetfence@httpd.admin.service' and 'journalctl -xn' for details.
Journal shows a time out (maybe according to the issue #1433), then:
/lib/systemd/system/packetfence@.service ->timeout 600
systemctl daemon-reload
apt-get install packetfence # again
Same error, but with pfcmd the admin service started:
/usr/local/pf/bin/pfcmd service httpd.admin start
and lsof -i showed the apache process listening on TCP 1443. 
3. Then:
apt-get install packetfence # again
now finished successfully(?):
Installation complete
Please fire up your Web browser [...]
but the initial configuration page isn't working (infinite connection attempts) and httpd.admin.error log shows lot of "Modification of a read-only value attempted." lines.

Sorry, I have no idea, how to trace this issue. Any help would be appreciated.

Note: this error also appeared on a working 6.3 instance, upgraded to 6.4 via apt-get upgrade and modified according to the upgrade asciidoc. No admin portal, no captive portal, no radius answers, lot of messages from httpd.aaa, httpd.webservices, httpd.portal.

**Comment by acseymour** [comment] 2016-11-26 01:43
I've experienced the exact same issue installing Packetfence 6.4 on a fresh install Debian 8.6 system, fully patched, installed on VMware. One thing I did noticed while trying to troubleshoot the issue is that I was able to get the configurator to launch if I executed the apache2 process manually from the command line as the root user with the debug option set. However, after the completing the initial configuration process, Packetfence still failed to start normally. All the httpd error logs contain the message "Modification of a read-only value".

**Comment by bklier** [comment] 2016-11-30 14:30
Same problem here, observed both while upgrading 6.3 to 6.4 using the Debian jessie package system and on a freshly installed Debian jessie system using the deb packages.

**Comment by thedoys** [comment] 2016-12-01 09:27
Same problem with new install on Debian Jessie

**Comment by fdurand** [comment] 2016-12-01 18:53
Can you try that:
dpkg -r --force-depends libposix-atfork-perl
apt-get update
apt-get install libposix-atfork-perl

and let me know.

**Comment by fdurand** [comment] 2016-12-01 21:45
Just an update, since jessie provide this lib, fetch it directly from the inverse repo https://inverse.ca/downloads/PacketFence/debian-lastrelease/pool/jessie/libp/libposix-atfork-perl/libposix-atfork-perl_0.02-1_amd64.deb

**Comment by thedoys** [comment] 2016-12-02 09:38
thanks you,

I will try

2016-12-01 22:45 GMT+01:00 Durand <notifications@github.com>:

**Comment by dwlfrth** [comment] 2016-12-05 14:43
Solution @fdurand provided is proven to be working.

dpkg -r --force-depends libposix-atfork-perl
Fetch https://inverse.ca/downloads/PacketFence/debian-lastrelease/pool/jessie/libp/libposix-atfork-perl/libposix-atfork-perl_0.02-1_amd64.deb
Install the newly fetched package

**Comment by fdurand** [comment] 2016-12-07 02:48
need to do a new package

**Comment by thedoys** [comment] 2016-12-07 07:39
no, it's work
but it seems a little bit touchy

Thanks you

2016-12-07 3:48 GMT+01:00 Durand <notifications@github.com>:

**Comment by github-jeff** [comment] 2016-12-08 03:45
Also having the same problem, the fdurand solution did not work in my case.  Fresh install on 8.6 with stable kernel allowed httpd.admin to run, but the configurator did not load.  Fresh install on 8.6 with backport kernel 4.7.1 does not allow httpd.admin to run at all.  Tried manual, and manual with debug mode, it does not start on reboot either.  The only time I was able to get httpd.admin running was just after the installation, but before a the first reboot.  Configurator did not load, even through everything seemed to be up.  Does Packetfence 6.3 running on 8.6 backport kernel work?  If not what is a solid combination (debian, kernel, and packetfence) to try?  I need to get this up and running, even if that means taking a step back on any and all revisions.

**Comment by jrouzierinverse** [comment] 2016-12-08 15:00
@github-jeff Do you see any errors in /usr/local/pf/logs/httpd.admin.error ?

**Comment by github-jeff** [comment] 2016-12-08 16:55
Yes.  Attempting to modify an read only value was the one that keeps
getting repeated.  The second was FQDN on the ServerName.  I have since
moved to CentOS 7, kernel-ml, ath10k-firmware.  That approach went into the
the exact same hardware flawlessly.  So that is a big hardware??? checkbox
we do not need to worry about.

I have tons of hardware here, and can run anything you had in mind.

Regards with thanks,
Jeff.

**Comment by wampratt** [comment] 2016-12-08 22:22
Same...
Jesssie, fresh install of 6.4.0-1.  Install was fine.  After reboot, apache run for a few seconds (port 1443 is open) but can not load config page, then apache shuts down. I see the same error messages  in httpd.admin.error (Modification of a read-only value attempted.)

Someone suggested reloading the config so I ran bin/pfcmd configreload
**root@cmp01-pf01:/usr/local/pf/bin# ./pfcmd configreload
Smartmatch is experimental at /usr/local/pf/lib/pf/cluster.pm line 588.
Could not write namespace config::PfDefault to L2 cache !
Could not write namespace config::Documentation to L2 cache !
Could not write namespace config::Cluster to L2 cache !
Could not write namespace config::Pf to L2 cache !
Could not write namespace interfaces to L2 cache !
Could not write namesp**....

Is this a file permission that I a adjust?
Thanks
Todd

**Comment by github-jeff** [comment] 2016-12-09 01:42
CentOS 7 fresh, kernel-ml, does load the configurator webapp exactly one
time.  After reboot it goes away forever, I cannot seem to figure out what
is killing the system but my guess is it's permissions somewhere, the error
codes are far too generic to figure out exactly where without deep
knowledge of all the inter-dependencies.  Some of the L2 problems I think
are based around the database not being setup yet.  Since I get one shot at
setting up the system, I have to wipe the system clean and start over again
with the hope that I can eventually sail through the installation all in
one go.

**Comment by github-jeff** [comment] 2016-12-09 05:22
Completed the configuration without an initial reboot, you cannot create
the vlan's using the application, it crashes, but you can assign types to
anything and they do save.  Everything else was pretty straight forward.
Step 7 was starting packetfence.  This step cycled through all the modules
and flipped them from stopped to started and then essentially killed
configurator webapp.  I have been unable to bring configurator or the
administration webapp up (tried locally and remotely).  I have now rebooted
a few times, and it appears as pretty much everything is running, including
httpd (must be 30 or so instances running with multiple instances of the
following: [admin, aaa, parking, portal, webservices, graphite]), but the
administration webapp does not load in any webbrowser (I tried a few).
Also lost access to remote terminal on port 22 after reboot.  The logs look
ok?!? or more specifically nothing is actively throwing errors.  I get a
ServerName error for localhost.localdomain now, which is wrong, I assume
those are supposed to be variables called from the main conf file, perhaps
that is not happening but that would not crash apache.

So what is really going on here?  I'll try rolling back to 6.3 tomorrow.
In any case, without really being able to look under the hood with the
admin webapplication, or anything throwing a specific error, debugging is
proving to be difficult.

Regards with thanks,
Jeff.

**Comment by julsemaan** [comment] 2016-12-09 13:00
@github-jeff 

The issues you are describing are completely out of scope for this issue.

Please use the mailing list to get help for those issues.

The scope of this one is httpd.admin crashing on Debian, that has nothing to do with what you are describing now

**Comment by github-jeff** [comment] 2016-12-09 14:26
This all involves Httpd.Admin, but I see your point, starting to take a left turn here.  Opened #1892 which includes CentOS 7 and Debian 8 as the problematic OS's as well.  Ubuntu 14.04 is not officially supported, but I tried that, and 16.04 as well, and not surprisingly it did not work out.

**Comment by fdurand** [comment] 2016-12-15 16:31
Debian jessie repo updated with the correct package.

**Closed as completed by fdurand** 2016-12-15 16:31 UTC
