### ISSUE TITLE
AD join fail after upgrade to samba 4.9.1

### ISSUE THREAD

**Issue by rossmeng** [inverse-inc/packetfence#4867] opened 2019-10-22 09:33 UTC
**Describe the bug**
CentOS already update, so the samba version also got updated to 4.9.1.
when I try to join my packetfence instance to my domain, it fails but it works before I use samba 4.8.3

**To Reproduce**
1. configure AD
2. join the packetfence into the domain

result:
Failed to join domain: failed to precreate account in ou cn=Computers,dc=QACAKE,dc=TEST: No such object

Do you see the issue in your test, any advice?  Thanks

**Comment by nqb** [comment] 2019-10-22 09:51
Hello,

Please use [packetfence-users mailing-list](https://packetfence.org/support.html#/community) for this kind of issue.

**Comment by julsemaan** [comment] 2019-10-24 11:49
This is an actual bug with PF using samba 4.9.1, not a user driven error/configuration

**Comment by julsemaan** [comment] 2019-10-24 11:54
Its due to specifying the location of the account. Ran the net ads join command without createcomputer=XYZ and it worked fine

See the following RHEL bug:
https://bugzilla.redhat.com/show_bug.cgi?id=1746122

Will investigate the potential solutions, it seems to be a samba bug

**Comment by julsemaan** [comment] 2019-10-24 12:09
It seems we'd have to use adcli or realmd to join the domain as a workaround which is not maintenance compatible.

The current workaround would be to pre-create the object when specifying a creation OU and to default to not specifying the parameter when creating in Computers which is the default value

**Comment by julsemaan** [comment] 2019-10-24 12:17
Discussed with @extrafu and we'll be doing the following:
1. Strip createcomputer=Computers when creating in the default OU which will mean joining with default location will work
2. Add notes in the help saying that if you specify an OU other than Computers you'll have to pre-create the account in the AD
3. Wait for the samba fix and revert the 2nd point. If samba fails to deliver a fix shortly then we can start working on integrating with realmd + adcli for the domain join.

**Comment by nqb** [comment] 2019-10-24 12:43
@julsemaan,

1. Are you able to reproduce the issue on a fresh CentOS 7.7 and not on a CentOS 7.6 ?

**Comment by julsemaan** [comment] 2019-10-24 12:52
@nqb, the bug is when you upgrade to CentOS 7.7 and then join the domain afterwards.

Existing domain joins are unaffected and joining on CentOS 7.6 works fine AFAIK

**Comment by julsemaan** [comment] 2019-10-24 12:53
Commits pushed for:

> Strip createcomputer=Computers when creating in the default OU which will mean joining with default location will work
> Add notes in the help saying that if you specify an OU other than Computers you'll have to pre-create the account in the AD

Will wait for the samba fix and will leave this opened to track this but will lower the priority

**Comment by nqb** [comment] 2019-10-24 13:00
I asked details on RedHat issue you mentioned because I didn't see any reference to a Samba upstream bug.

**Comment by nqb** [comment] 2019-10-24 13:04
https://bugzilla.samba.org/show_bug.cgi?id=14007

Samba already provides a patch.

**Comment by nqb** [comment] 2019-12-04 06:20
Samba patch has been merged into CentOS 7.7: https://access.redhat.com/errata/RHBA-2019:3969

**Comment by jrouzierinverse** [comment] 2021-08-19 17:27
Can this be closed?

**Closed as completed** 2021-08-20 05:47 UTC
Labels: Type: Bug, Priority: Medium
