### ISSUE TITLE
LDAP cache issue

### ISSUE THREAD

**Issue by dwlfrth** [inverse-inc/packetfence#2786] opened 2017-11-20 20:17 UTC
There seems to be an issue with #2560.
Everytime the cache is being hit a second time,  the result is not getting returned properly, therefore, the result of the LDAP match is wrong.

Following test script called 'auth1.pl'

use strict;
use warnings;
use lib qw(/usr/local/pf/lib);
use pf::authentication;
use Data::Dumper;

print Dumper(
    pf::authentication::match(
        'NSA-AD',
        {
            realm           => 'undef',
            SSID            => 'SSID-Open',
            connection_type => 'Wireless-802.11-NoEAP',
            mac             => 'de:ad:be:ef:00:42',
            username        => 'esnowden'
        },
        'set_role'
    )
);

returns

[root@pfb pf]# perl auth1.pl 
$VAR1 = 'openStaff';
[root@pfb pf]# perl auth1.pl 
$VAR1 = 'openOther';
[root@pfb pf]# perl auth1.pl 
$VAR1 = 'openOther';
[root@pfb pf]# perl auth1.pl 
$VAR1 = 'openOther';
[root@pfb pf]# perl auth1.pl 
$VAR1 = 'openOther';

**Comment by julsemaan** [comment] 2018-01-10 14:19
@jrouzierinverse 

Where is the fix for this ?

And it would be really useful to have this put in the maintenance after confirmation that the issue is resolved since all setups using the LDAP cache are currently broken

**Comment by julsemaan** [comment] 2018-03-12 18:48
@jrouzierinverse 

This is still an issue and LDAP cache is still broken in 7.4

Could you point me to the fix so we can put this in maintenance and get LDAP cache working again

**Comment by jrouzierinverse** [comment] 2018-03-12 19:28
Are you asking if it is fixed or telling me it is broken?

**Comment by julsemaan** [comment] 2018-03-12 19:31
You created the fix about 2 months ago, you needed to test it and then were going to put it in the maintenance.

Seems the bug is in 7.4 patches with the latest maintenance patches so we just need to get this fixed and in the maintenance for the affected versions

**Closed as completed** 2018-04-04 20:07 UTC
Labels: Type: Bug, Priority: High
