### ISSUE TITLE
Web Admin - SSL certificates: Can't save multiples CAs.

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5299] opened 2020-04-06 16:00 UTC
It works but saves only the top certs all the time.

**Comment by julsemaan** [comment] 2020-04-06 16:35
This was always like this, the API doesn't currently support multiple CAs

We should tackle this feature for 10.1 and potentially combine this with the work @fdurand is doing for the multiple EAP-TLS configs

**Comment by nqb** [comment] 2020-04-07 05:25
Duplicate of #5061

**Closed as completed by nqb** 2020-04-07 05:25 UTC
Labels: Type: Feature / Enhancement, Priority: Medium
