### ISSUE TITLE
(winbindd-wrapper): chatty log message "Re-registering"

### ISSUE THREAD

**Issue by antonc42** [inverse-inc/packetfence#4019] opened 2019-02-22 14:08 UTC
I recently pulled in the maintenance fixes for 8.2 using `/usr/local/pf/addons/pf-maint.pl` to fix a chatty log message (see issue #4014 and thanks for the fix!). Now I have an even more chatty log message from "winbindd-wrapper". Approximately every six seconds, there is a log message:

```
packetfence_winbindd-wrapper: winbindd-wrapper(XXXX) WARN: [mac:[undef]] Re-registering <DomainName> (main::child_sighandler)
```

`XXXX` is the PID of winbindd-wrapper
`<DomainName>` is the name of my configured Active Directory Domain

I see that this log message was added recently in commit 67dc40aaeb8127be2b520204b3462d54bcb79e3b. I'm not sure if this indicative of a problem with my install or if there is a problem with the log message. Should this re-registering be taking place every six seconds?

**Comment by julsemaan** [comment] 2019-02-22 14:32
This likely means your winbindd process is dying which leads to the master process (winbindd-wrapper) respawning it.

If you performed the upgrade of samba/winbindd recently, you may have to kill off the old childs since a recent change caused issues requiring to rework the wrapper.

You can either:
```
pkill -9 -f winbindd
``` 
or 
```
reboot
```

**Comment by julsemaan** [comment] 2019-02-22 14:33
I'll close this for now, re-open if that doesn't fix it

**Closed as completed by julsemaan** 2019-02-22 14:33 UTC
Labels: Type: Bug, Priority: Low

**Comment by antonc42** [comment] 2019-02-22 14:37
That seems to have done it. I had tried to restart the winbindd-wrapper, but I didn't think to check for other running processes. Thanks!

**Comment by nqb** [comment] 2019-04-25 13:05
I can confirm that @julsemaan's solution works.

**Comment by olmanolsztyn** [comment] 2021-10-08 10:19
Hi i done @julsemaan steps but still got tis WARN:
After kill i got logs

'WARN: Problem trying to run command: LANG=C sudo /usr/local/pf/addons/create_chroot.sh DOMAIN /chroots called from manager::winbindd::build_namespaces. Child exited with non-zero value 1 (pf::util::pf_run)'

and see one child zombie process

'root       11517  0.6  1.4 256868 230288 ?       Ss   12:12   0:02 winbindd-wrapper
root       11889  0.0  0.0      0     0 ?        Z    12:19   0:00 [winbindd] <defunct>'

**Comment by julsemaan** [comment] 2021-10-08 11:38
@olmanolsztyn 

You're unlikely to be hitting a 2+ years old issue in our recent release.

This is likely because your domain configuration is wrong or unjoined.

**Comment by olmanolsztyn** [comment] 2021-10-08 12:12
Yes thats the problem. I have one AD ujnoined.
Thanks for response.
