### ISSUE TITLE
Issues with upgrading 11.0 to 11.1 on Debian via packetfence-upgrade 

### ISSUE THREAD

**Issue by heapdavid** [inverse-inc/packetfence#6676] opened 2021-11-02 17:28 UTC
**Describe the bug**

I used the official upgrade script last night (`apt install packetfence-upgrade && /usr/local/pf/addons/full-upgrade/run-upgrade.sh`) to upgrade packetfence from pf11.0 to 11.1, and the script seemed to complete without errors.

Today after an `apt dist-upgrade` noticed that the first script did not seem to have upgraded packetfence beyond changing the repos as this happened:
```
Unpacking packetfence (11.1.0+20211029155140+399133947+0011+maintenance\~11.1+bullseye1) over (11.0.0+20211028192958+397927886+0011+maintenance\~11.0+bullseye1)
...
```
nor upgraded the database schema:
```
$ /usr/local/pf/bin/pfcmd service pf restart
Synchronizing state of monit.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install disable monit
Service                                                 Status    PID
Checking configuration sanity...
FATAL - The PacketFence database schema version '11.0' does not match the current *minor* installed version '11.1'
Please refer to the UPGRADE guide on how to complete an upgrade of PacketFence
```

Rerunning the script provided by PF 11.1 seemed to resolve the issue. 

**To Reproduce**
1. Install pf 11.0 on Debian 11
2. Upgrade to 11.1 using packetfence-upgrade script as per docs
3. Run `apt dist-upgrade` for maintenance versions
4. Try to restart pf services

**Expected behavior**
The first script to complete the upgrade

**Additional context**
Unfortunately I don't have another packetfence to verify this on so the steps to reproduce are untested

**Comment by lzammit** [comment] 2021-11-02 17:43
Hello David,

Are you on a standalone or a cluster ?

Thanks,

Ludovic Zammit
Product Support Engineer Principal

Cell: +1.613.670.8432
Akamai Technologies - Inverse
145 Broadway
Cambridge, MA 02142
Connect with Us:	 <https://community.akamai.com/>  <http://blogs.akamai.com/>  <https://twitter.com/akamai>  <http://www.facebook.com/AkamaiTechnologies>  <http://www.linkedin.com/company/akamai-technologies>  <http://www.youtube.com/user/akamaitechnologies?feature=results_main>

**Comment by nqb** [comment] 2021-11-03 06:31
Hello @heapdavid,

I performed the same operation yesterday without any errors. 

Do you have logs of execution of `run-upgrade.sh` ? Without this, it will be hard to identify root cause of issue.

EDIT: Based on your comment, it looks like `run-upgrade.sh` as performed some steps like changing repository definition because you were able to get new packages when you performed `apt dist-upgrade`

**Comment by heapdavid** [comment] 2021-11-03 09:59
>Are you on a standalone or a cluster ?

It's a standalone packetfence

> Do you have logs of execution of `run-upgrade.sh`

Does it log to anywhere in particular or just the stdout? If not, I don't sorry. I just thought i'd flag this up in case someone else comes across it.

>it looks like `run-upgrade.sh` as performed some steps like changing repository definition

Yes that's how it looks to me too.

**Comment by nqb** [comment] 2021-11-03 11:12
> Does it log to anywhere in particular or just the stdout? If not, I don't sorry. I just thought i'd flag this up in case someone else comes across it.

Unfortunately not, I opened #6678 to add this feature in next versions.

I will close this issue for now. Feel free to re-open if you got more details.

**Closed as completed by nqb** 2021-11-03 11:12 UTC
Labels: Type: Bug

**Comment by heapdavid** [comment] 2021-11-04 16:48
Just by way of an update, it looks like this was caused by some of the apt pinning we do internally for deployment not being updated before the run - the script would have been unable to update past 11.0 when it ran the first time. Sorry for taking up your time!
