### ISSUE TITLE
Admin roles: Allowed node roles not taken into account

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4854] opened 2019-10-14 09:39 UTC
When a user has an admin role with a limited list of `Allowed node roles`, he is able to create nodes with all roles (not only `Allowed node roles`).

**To Reproduce**
1. Create two roles: `role1` and `role2`
1. Create an admin role called `Role-1`
   * Actions: Nodes - Create
   * Node options - Allowed node roles: `role1`
1. Create a user `foo` and assign `Role-1` as access level
1. Log in as `foo` user and try to create a node with `role2`

=> Node is created.

**Expected behavior**
User `foo` should be able to create only nodes with role `role1`.

**Comment by julsemaan** [comment] 2019-10-15 11:23
This is a duplicate of https://github.com/inverse-inc/packetfence/issues/4536

**Comment by nqb** [comment] 2019-10-15 11:40
@julsemaan, I've seen this issue too. It's related to Users not to Nodes.

I reopen, let me know if you disagree.

**Comment by julsemaan** [comment] 2019-10-15 12:24
#4558 which fixes #4536 doesn't look to be specific to nodes or users.

@jrouzierinverse can confirm and close this accordingly

**Comment by extrafu** [comment] 2019-10-17 14:28
@jrouzierinverse Please provide an update.

**Comment by jrouzierinverse** [comment] 2019-10-17 18:29
#4558 will do the same thing for both users and nodes.
However, #4558 is incomplete will need to look at what else is needed to fix it.

**Closed as completed** 2019-11-21 14:35 UTC
Labels: Type: Bug, Priority: Medium
