### ISSUE TITLE
pfcron outputs errors about a table not existing

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6544] opened 2021-08-24 13:30 UTC
**Describe the bug**
Here is the error:
```
Aug 24 09:29:18 test-fresh-lt pfcron[47543]: t=2021-08-24T09:29:18-0400 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=47543
Aug 24 09:29:18 test-fresh-lt pfcron[47543]: t=2021-08-24T09:29:18-0400 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=47543
Aug 24 09:29:18 test-fresh-lt pfcron[47543]: t=2021-08-24T09:29:18-0400 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=47543
Aug 24 09:29:18 test-fresh-lt pfcron[47543]: t=2021-08-24T09:29:18-0400 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=47543
```

Not sure what that table is

**Comment by jrouzierinverse** [comment] 2021-08-24 14:48
Can you show the output of the SQL command.
```SHOW GRANTS FOR 'pf'@'localhost';```

**Comment by julsemaan** [comment] 2021-08-24 16:39
> SHOW GRANTS FOR 'pf'@'localhost';

Here it is:
```
MariaDB [(none)]> SHOW GRANTS FOR 'pf'@'localhost';
+-------------------------------------------------------------------------------------------------------------------+
| Grants for pf@localhost                                                                                           |
+-------------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `pf`@`localhost` IDENTIFIED BY PASSWORD '*54C0E997504DBEFCE087C95CB283D3D758DE5E64'         |
| GRANT SELECT, INSERT, UPDATE, DELETE, CREATE TEMPORARY TABLES, LOCK TABLES, EXECUTE ON `pf`.* TO `pf`@`localhost` |
| GRANT SELECT ON `mysql`.`proc` TO `pf`@`localhost`                                                                |
| GRANT DROP ON `pf`.`radius_nas` TO `pf`@`localhost`                                                               |
+-------------------------------------------------------------------------------------------------------------------+
4 rows in set (0.000 sec)
```

**Comment by extrafu** [comment] 2021-08-26 11:49
@julsemaan and @jrouzierinverse if there's no other evidence and the issue can't be reproduced, close it or move it out of the v11 release.

**Comment by julsemaan** [comment] 2021-08-26 13:49
I actually found the reference to this table. Its in pf-schema-X.Y.sql in the `bandwidth_aggregation` stored proc

Not sure why its erroring out though

**Comment by jrouzierinverse** [comment] 2021-08-30 20:35
We are moving this to 11.1

**Comment by extrafu** [comment] 2021-08-31 11:31
What is discussed with other team members?

**Comment by julsemaan** [comment] 2021-08-31 11:37
> What is discussed with other team members?

Yes me and djamaisse had a call yesterday to discuss this specific matter.
In summary: the fix has too much potential for regressions at this stage of the release and the reproducibility of the issue isn't consistent enough and seems to be temporary so it could be pfcron trying to do something before the pf DB user has enough rights.

Bottom line is, the accounting works according to our QA and this is what it touches so we should be fine implementing the fix for 11.1, worst case, back-porting to the maintenance if absolutely necessary

**Comment by extrafu** [comment] 2021-08-31 11:40
Thanks for the clarifications.

**Comment by extrafu** [comment] 2021-10-13 13:15
Closing for now - unable to reproduce.

**Comment by nqb** [comment] 2022-01-21 08:22
I noticed this behavior on a 11.1 cluster setup with packetfence packages: `11.1.0+20211224073808+436568439+0011+maintenance~11.1+bullseye1`

On first server in the cluster, I can see following error messages each minute:

```
#  journalctl -u packetfence-pfcron -f
[..]
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 packets.go:36: unexpected EOF
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 packets.go:122: closing bad idle connection: EOF
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 connection.go:158: driver: bad connection
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 packets.go:122: closing bad idle connection: EOF
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 connection.go:158: driver: bad connection
Jan 21 09:10:26 pfe01-m pfcron[96283]: t=2022-01-21T09:10:26+0100 lvl=eror msg="Database error: invalid connection" pid=96283
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 packets.go:122: closing bad idle connection: EOF
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 connection.go:158: driver: bad connection
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 packets.go:122: closing bad idle connection: EOF
Jan 21 09:10:26 pfe01-m pfcron[96283]: [mysql] 2022/01/21 09:10:26 connection.go:158: driver: bad connection
Jan 21 09:10:26 pfe01-m pfcron[96283]: t=2022-01-21T09:10:26+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=96283
Jan 21 09:10:26 pfe01-m pfcron[96283]: t=2022-01-21T09:10:26+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running ip6log_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running password_of_the_day" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running ip4log_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running nodes_maintenance" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running acct_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running cluster_check" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running locationlog_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running auth_log_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running dns_audit_log_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running security_event_maintenance" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running acct_maintenance" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running radius_audit_log_cleanup" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Running bandwidth_maintenance" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/acct_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/cluster_check/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/security_event_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/password_of_the_day/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/nodes_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Request isn't authorized, performing login against the Unified API" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/login" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Request isn't authorized, performing login against the Unified API" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/login" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="dns_audit_log_cleanup cleaned items 0" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_process' doesn't exist" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="auth_log_cleanup cleaned items 0" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Request isn't authorized, performing login against the Unified API" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/login" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="radius_audit_log_cleanup cleaned items 148" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Request isn't authorized, performing login against the Unified API" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/login" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/acct_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Request isn't authorized, performing login against the Unified API" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/login" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/security_event_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/cluster_check/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/password_of_the_day/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=eror msg="Database error: Error 1146: Table 'pf.to_delete' doesn't exist" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="Calling Unified API on uri: https://127.0.0.1:9999/api/v1/config/maintenance_task/nodes_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="API call /api/v1/config/maintenance_task/acct_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="API call /api/v1/config/maintenance_task/nodes_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="API call /api/v1/config/maintenance_task/security_event_maintenance/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="API call /api/v1/config/maintenance_task/password_of_the_day/run" pid=96283
Jan 21 09:10:36 pfe01-m pfcron[96283]: t=2022-01-21T09:10:36+0100 lvl=info msg="API call /api/v1/config/maintenance_task/cluster_check/run" pid=96283
```
When I extract logs above: `pfacct` is stopped on the whole cluster.
There is also a `pf.to_process` table which is mentioned.

When I saw this errors on pf1, on pf3, I can see following request:

```
MariaDB [pf]> show full processlist;
[..]
| 268953 | root        | localhost:40522     | pf   | Execute |     24 | Sending data            | INSERT INTO to_delete SELECT node_id, tenant_id, mac, DATE(time_bucket) as new_time_bucket, time_bucket, in_bytes, out_bytes FROM bandwidth_accounting_history WHERE time_bucket <= '2022-01-20 09:17:35' AND time_bucket != DATE(time_bucket) LIMIT 100 |    0.000 |
```

It can be wrong but it looks like this process is using MariaDB socket (in place of haproxy-db) to make changes which can certainly cause issues.

**Comment by nqb** [comment] 2022-01-24 07:38
After I truncated `bandwidth_maintenance` table, there is no database error messages anymore but still these errors:

```
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 packets.go:122: closing bad idle connection: EOF
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 connection.go:158: driver: bad connection
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 packets.go:122: closing bad idle connection: EOF
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 connection.go:158: driver: bad connection
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 packets.go:122: closing bad idle connection: EOF
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 connection.go:158: driver: bad connection
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 packets.go:122: closing bad idle connection: EOF
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 connection.go:158: driver: bad connection
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 packets.go:122: closing bad idle connection: EOF
Jan 24 08:35:36 pfe01-m pfcron[96283]: [mysql] 2022/01/24 08:35:36 connection.go:158: driver: bad connection

```

**Comment by jrouzierinverse** [comment] 2023-01-22 21:54
This has been fixed after getting rid of using temp tables for cleanup.

**Closed as completed by jrouzierinverse** 2023-01-22 21:54 UTC
Labels: Type: Bug, Priority: High
