### ISSUE TITLE
#pf12 domain join 

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#7095] opened 2022-08-10 20:24 UTC
**Describe the bug**
When you create a domain configuration and save it, the admin gui start to do some request 

**To Reproduce**
1. Active Directory Domain then create a new one
2. Click on save 

**Screenshots**
Output:

```
Request URL: https://172.20.136.0:1443/api/v1/pfqueue/task/Task:99723970-d124-48a6-8edf-8b5af81c2053:Queue:general:domain/status/poll
Request Method: GET
Status Code: 200 OK
Remote Address: 172.20.136.0:1443
Referrer Policy: strict-origin-when-cross-origin
content-length: 159
content-type: application/json
date: Wed, 10 Aug 2022 20:18:29 GMT
server: Caddy
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Authorization: Bearer 05ec4f4d5014aeb47e63d1dfb85f1b963b8f2676f454a09085206975fbda69f6
Connection: keep-alive
Cookie: CGISESSION=ee3f02a2fc771826e50d7a5196e18e5312c06e82
DNT: 1
Host: 172.20.136.0:1443
Referer: https://172.20.136.0:1443/admin
sec-ch-ua: ".Not/A)Brand";v="99", "Google Chrome";v="103", "Chromium";v="103"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Linux"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.0.0 Safari/537.36
```
![image](https://user-images.githubusercontent.com/1553962/184012866-bc64e88a-02c2-435f-acf0-549c9b03c130.png)

**Expected behavior**

It should only test one time to see that the server is not joined

**Comment by satkunas** [comment] 2022-08-11 18:04
This was a regression caused by a recent commit. I've provided a fix in https://github.com/inverse-inc/packetfence/commit/5a856b4cb7ab29cc1ddaed6d864193e8d6ad2d64

I'm waiting to see if no further regressions are created before closing this issue, or continuing further on an other solution.

**Closed as completed** 2022-08-11 18:41 UTC
Labels: Type: Bug, Priority: High
