### ISSUE TITLE
Creation of rule does not set match parameter in config file

### ISSUE THREAD

**Issue by thmichel** [inverse-inc/packetfence#850] opened 2015-08-20 11:41 UTC
I already asked this on the mailing list, but I think this may be a bug so posting it here as well, sorry for the double post.

I created an LDAP source with some rules via the Web GUI of Packetfence (running current version on CentOS 6). None of these rules seemed to work, except a catch-all route without conditions.

I found that in authentication.conf for each rule there was a line "match = ". When changing that to "match = all", the rules started working.

I could not find a switch in the GUI to enable that match parameter, am I missing something?

**Comment by virtualgiraffe** [comment] 2015-08-21 11:03
Hi

I too have seen this. I spent a loooong 24hrs puzzling over it and eventually found the cause... This is a bug in the templates. I'm a PF newb and not familiar with the template tech, but it is relatively easy to fix once you know how. I'd like to see this fixed in the source though...

If you look at the rule editing modal window you'll notice text which reads

  `If [.....] of the following:`

or similar -- where [....] is a bunch of HTML code intended to render a dropdown control containing "any" and "all". 

The dialog is rendered by via the template:

   `/usr/local/pf/html/pfappserver/root/authentication/source/rule_read.tt`

In this file you will find a line:

  `<dt>[% l('If [_1] of the following conditions are met:', [ form.field('match').render_element ]) | none %]</dt>`

The `[_1]` is a placeholder for the control rendered by `(form.field(...))`. However it renders it inside `l()`. I assume `l()` translates to "literal" or some such. Without investigating further I replaced this line with:

  `<dt>If [% form.field('match').render_element | none %] of the following:</dt>`

and now the control renders just fine and rules work as you would expect. 

Hope this helps

Jonathan

**Comment by virtualgiraffe** [comment] 2015-08-21 11:08
Note to developers: as I guess you know there are multiple templates containing `l('...[_1]...')` and each of them results in a similar issue.

Red Hat Enterprise Linux Server release 6.6 (Santiago)
PacketFence 5.3.1 (via PF repo/yum as documented)

Jonathan

**Comment by thmichel** [comment] 2015-08-21 11:15
Hi Jonathan,

thanks a lot for that. It took me more than 24hrs to find out why my rules
didn't work :-)

I already reported this as bug in github.

Regards,

Tom.

Zitat von virtualgiraffe <notifications@github.com>:

> Hi
>
>   I too have seen this. I spent a loooong 24hrs puzzling over it and
> eventually found the cause... This is a bug in the templates. I'm a PF
> newb and not familiar with the template tech, but it is relatively easy
> to fix once you know how. I'd like to see this fixed in the source
> though...
>
>   If you look at the rule editing modal window you'll notice text which
> reads
>
>   "if [.....] of the following:"
>
>   or similar -- where [....] is a bunch of HTML code intended to render
> a dropdown control containing "any" and "all".
>
>   The dialog is rendered by via the template:
>
>   /usr/local/pf/html/pfappserver/root/authentication/source/rule_read.tt
>
>   In this file you will find a line:
>
>   <dt>[% l('If [_1] of the following conditions are met:', [
> form.field('match').render_element ]) | none %]</dt>
>
>   The [_1] is a placeholder for the control rendered by
> (form.field(...)). However it renders it inside l(). I assume l()
> translates to "literal" or some such. Without investigating further I
> replaced this line with:
>
>   <dt>If [% form.field('match').render_element | none %] of the
> following:</dt>
>
>   and now the control renders just fine and rules work as you would
> expect.
>
>   Hope this helps
>
>   Jonathan
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1]  
https://github.com/inverse-inc/packetfence/issues/850#issuecomment-133373361

**Comment by thmichel** [comment] 2015-08-21 11:16
Me again,

just saw that you replied to the github entry, so you already know -
thought your mail came via the mailing list.

Zitat von virtualgiraffe <notifications@github.com>:

> Hi
>
>   I too have seen this. I spent a loooong 24hrs puzzling over it and
> eventually found the cause... This is a bug in the templates. I'm a PF
> newb and not familiar with the template tech, but it is relatively easy
> to fix once you know how. I'd like to see this fixed in the source
> though...
>
>   If you look at the rule editing modal window you'll notice text which
> reads
>
>   "if [.....] of the following:"
>
>   or similar -- where [....] is a bunch of HTML code intended to render
> a dropdown control containing "any" and "all".
>
>   The dialog is rendered by via the template:
>
>   /usr/local/pf/html/pfappserver/root/authentication/source/rule_read.tt
>
>   In this file you will find a line:
>
>   <dt>[% l('If [_1] of the following conditions are met:', [
> form.field('match').render_element ]) | none %]</dt>
>
>   The [_1] is a placeholder for the control rendered by
> (form.field(...)). However it renders it inside l(). I assume l()
> translates to "literal" or some such. Without investigating further I
> replaced this line with:
>
>   <dt>If [% form.field('match').render_element | none %] of the
> following:</dt>
>
>   and now the control renders just fine and rules work as you would
> expect.
>
>   Hope this helps
>
>   Jonathan
>
>   —
> Reply to this email directly or view it on GitHub[1].
>       



Links:
------
[1]  
https://github.com/inverse-inc/packetfence/issues/850#issuecomment-133373361

**Comment by virtualgiraffe** [comment] 2015-08-21 11:25
Hi Tom

You're welcome! I'm just relieved to find I was not the only one 
scratching my head ;-).

Jonathan

**Comment by julsemaan** [comment] 2015-08-21 18:54
This was already fixed and available though the maintenance branch of packetfence (along with other template fixes)

You can apply it using : /usr/local/pf/addons/pf-maint.pl

This will be included in 5.3.2 or 5.4 whichever comes first

**Comment by virtualgiraffe** [comment] 2015-08-24 08:49
Many thanks, Julien, for pointing out the maintenance script!

**Closed as completed** 2016-10-14 13:33 UTC
