### ISSUE TITLE
Add and Delete Buttons Hidden in Authentication Conditions - Webgui

### ISSUE THREAD

**Issue by cheiy** [inverse-inc/packetfence#2741] opened 2017-10-31 13:45 UTC
When trying to add conditions under Authentication Sources, the - and + buttons are hidden (especially for AD authentication sources) as shown in image1; I tried on both Firefox (Version 56.0.2) and Chrome ( Version 61.0.3163.100 ) but the problem persisted.

Possible Solution
The solution I found is to edit the .css file that provides styling to the page, i.e, styles.css found under the /usr/local/pf/html/pfappserver/root/static/css/ folder by adding margin-right:30px to the form-horizontal .control-group definition. Please see attached modified style.css - you may copy it to the path after performing a backup of the existing one (just in case).
See image2 for the end result.
![image1](https://user-images.githubusercontent.com/10514203/32226927-ea1aad46-be5a-11e7-8dda-cfd213955bde.JPG)
![image2](https://user-images.githubusercontent.com/10514203/32226928-eab0c3ee-be5a-11e7-8cc4-3db680c8799b.JPG)

**Comment by julsemaan** [comment] 2017-10-31 13:59
This is a duplicate of #2678

Will close this one, you can refer to the other issue for follow up

Cheers

**Closed as completed by julsemaan** 2017-10-31 13:59 UTC
