### ISSUE TITLE
API - Routed Networks meta race condition

### ISSUE THREAD

**Issue by satkunas** [inverse-inc/packetfence#5344] opened 2020-04-09 12:59 UTC
When fetching the meta for routed_networks using the CLI the key `pool_backend` appears 100% of the time:

`/usr/local/pf/sbin/pfperl-api get -M OPTIONS /api/v1/config/routed_networks | jq '.meta.pool_backend'`
```json
{
  "allowed": [
    {
      "text": "Memory Pool",
      "value": "memory"
    },
    {
      "text": "MySQL Pool",
      "value": "mysql"
    }
  ],
  "default": "memory",
  "placeholder": null,
  "required": true,
  "type": "string"
}
```

However, when fetching meta via the API the key `pool_backend` only appears 50% of the time:

Good:
![Screenshot_20200409_085827](https://user-images.githubusercontent.com/3904468/78897502-49a0ec00-7a40-11ea-9f31-c13d7584bc41.png)

Bad (request only a few seconds after the previous):
![Screenshot_20200409_085901](https://user-images.githubusercontent.com/3904468/78897574-65a48d80-7a40-11ea-8ac6-9c3f876a95da.png)

**Comment by extrafu** [comment] 2020-04-14 19:05
Unable to reproduce for now, closing. Reopen if necessary with all evidences.

**Closed as completed by extrafu** 2020-04-14 19:05 UTC
Labels: Type: Bug, Priority: Critical, API
