### ISSUE TITLE
Don't have access to the admin config anymore

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5533] opened 2020-06-04 19:47 UTC
**Describe the bug**
Login the admin gui and you will see that:

![image](https://user-images.githubusercontent.com/1553962/83803455-97218a00-a67a-11ea-865b-0fe41301c5a5.png)

Latest devel package packetfence-10.0.9-20200604191719.153015668.0007.devel.el7.x86_64

**Comment by jrouzierinverse** [comment] 2020-06-05 11:24
I think @julsemaan and @satkunas would need to look into this.
From what I gathered the Admin is sending the X-PacketFence-Tenant-Id:0
However, the tenant id in the token is 1.

**Comment by fdurand** [comment] 2020-06-05 11:38
I changed to 1 on my setup and it's ok now (at least i can continue to test)
https://github.com/inverse-inc/packetfence/commit/eee29514d9589735b540555f099a2306ea317c9e

**Comment by satkunas** [comment] 2020-06-05 11:53
@jrouzierinverse possibly related to https://github.com/inverse-inc/packetfence/issues/5532

**Comment by jrouzierinverse** [comment] 2020-06-05 12:12
@satkunas this happens before it hits the pfperl-api

**Comment by satkunas** [comment] 2020-06-05 12:26
>  the Admin is sending the X-PacketFence-Tenant-Id:0

@jrouzierinverse this is intentional by @julsemaan request.

**Comment by jrouzierinverse** [comment] 2020-06-05 13:18
The issue seems to be the combination of that and the check in the authorization layer in the api-frontend.

**Comment by jrouzierinverse** [comment] 2020-06-05 14:20
I made a fix not sure if the workflow is correct. @julsemaan close this if you think it is the correct thing to do.

**Comment by fdurand** [comment] 2020-06-05 15:04
![image](https://user-images.githubusercontent.com/1553962/83892257-61cd7880-a71c-11ea-9e6f-003c54f5b779.png)

**Comment by lzammit** [comment] 2020-06-05 16:44
Same error as fabrice

**Comment by jrouzierinverse** [comment] 2020-06-05 17:48
You would need to update your DB with the global tenant

**Comment by nqb** [comment] 2020-06-08 09:40
With latest devel builds, I'm able to access Configuration menu. I keep issue opened if @julsemaan wants to add something. I will open a new issue related to tenant.

**Comment by julsemaan** [comment] 2020-06-08 11:46
> > the Admin is sending the X-PacketFence-Tenant-Id:0
> 
> @jrouzierinverse this is intentional by @julsemaan request.

@satkunas, I think we misunderstood eachother. What I said is to always use the token ID in the token_info. In this case the token_info contains 1 so there is no reason for the admin to be using `X-PacketFence-Tenant-Id: 0`

**Closed as completed** 2020-06-08 14:17 UTC
Labels: Type: Bug, Priority: Critical

**Comment by julsemaan** [comment] 2020-06-08 16:38
I confirmed in multi-tenant mode, everything is still behaving as expected
