### ISSUE TITLE
webadmin (reports): unable to browse additional pages

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#4675] opened 2019-07-19 08:24 UTC
When you go in Reports menu and try to display, for example, `Standard Report / Node / Active`, you will be able to display only the first page of your report. If you click on other pages, nothing happens.

**To Reproduce**
1. Go to Standard Report / Node / Active
2. Click on '2' to display second page of report

**Expected behavior**
Web admin should display second page of report.

**Comment by satkunas** [comment] 2019-09-04 20:54
`/api/v1/reports` endpoint does not currently support pagination variables (`limit`, `cursor`).

@julsemaan will need to implement this first in the backend before I can add it to the frontend.

Reassigning to @julsemaan

**Comment by julsemaan** [comment] 2019-09-05 13:06
@satkunas, you actually wrote the API calls for those reports so I'll defer to you for what to do with them

The current controller glues together the API and the outdated report.pm module which didn't support pagination by design so here are the options I can think of:
- We stop having pagination of these reports in the frontend because the existing reports do not support it by design
- We adjust the existing report.pm queries and functions so they support pagination resulting in duplicated logic. I'm far from being a fan of this option especially because report.pm isn't built using the DAL and we'll have to duct tape this through copy/pasted code duplication (or migrate to the DAL)
- Instead of having 2 different reports APIs, we merge these reports in the dynamic reports (so in the config itself) so that we don't have to manage these legacy functions in report.pm and can kill it with fire once the old admin goes away. I'd just take my axe and destroy the existing /api/v1/reports and get the report.pm based reports logic in reports.conf.defaults and they'll magically appear

**Comment by satkunas** [comment] 2019-09-05 21:50
@julsemaan I will go ahead with the first option, It's the least invasive ATM. Deprecating the Standard Reports and moving them to the other section will leave them without a graphical chart (table only), so we'll need to discuss this further before sharpening the axe.

**Comment by julsemaan** [comment] 2019-09-06 12:09
>  so we'll need to discuss this further before sharpening the axe.

![image](https://user-images.githubusercontent.com/3857942/64426802-8c9b7b00-d07d-11e9-91f6-01edbcc72af7.png)

**Closed as completed** 2019-09-06 13:32 UTC
Labels: Type: Bug, Priority: Medium
