### ISSUE TITLE
PF Admin: Does not display wrong password at the login

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2191] opened 2017-04-03 20:34 UTC
If you put a wrong password at the login it won't say it's not correct or wrong.

**Comment by jrouzierinverse** [comment] 2017-04-03 20:45
This is a feature not a bug.
If the admin specifies wrong password vs username it could allow leaking of valid usernames.

I would say close this one

**Comment by julsemaan** [comment] 2017-04-04 11:18
This is actually a bug because its not displaying that the credentials are invalid like it used to

It just displays nothing now like if you didn't submit the form

So we shouldn't close as this is a regression

**Closed as completed** 2017-04-04 13:09 UTC
Labels: Type: Bug
