### ISSUE TITLE
configurator (Debian): unable to finish configurator

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#5358] opened 2020-04-14 07:25 UTC
**Describe the bug**
When you reach end of configurator and click on "Start PacketFence" button, you got following error:
```
Request failed with status code 504
service/pf/start
```

**To Reproduce**
1. Complete all steps of configurator on Debian
2. Click on 'Start PacketFence' at step 4

**Expected behavior**
Redirection to web admin.

**Additional context**
In `/usr/local/pf/logs`:
```
Apr 14 07:08:52 pfdeb9dev packetfence: INFO pfperl-api(18505): Stopping haproxy-admin with pid 18515 (pf::services::manager::stopService)
Apr 14 07:08:52 pfdeb9dev packetfence: INFO pfperl-api(18505): Stopping haproxy-admin with pid 18515 (pf::services::manager::stopService)
Apr 14 07:08:52 pfdeb9dev pfhttpd[18493]: 14/Apr/2020:07:08:52 +0000 [ERROR 499 /api/v1/configurator/service/haproxy-admin/restart] context canceled
Apr 14 07:08:52 pfdeb9dev packetfence: INFO pfperl-api(18505): child exited with value 0
 (pf::services::manager::stopService)
Apr 14 07:08:52 pfdeb9dev packetfence: INFO pfperl-api(18505): child exited with value 0
 (pf::services::manager::stopService)
Apr 14 07:08:52 pfdeb9dev pfhttpd: 14/Apr/2020:07:08:52 +0000 [ERROR 499 /api/v1/configurator/service/haproxy-admin/restart] context canceled
Apr 14 07:08:52 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:08:52 +0000] "POST /api/v1/configurator/service/pf/update_systemd HTTP/1.1" 200 49 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 07:08:52 pfdeb9dev pfhttpd: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:08:52 +0000] "POST /api/v1/configurator/service/pf/update_systemd HTTP/1.1" 200 49 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 07:08:52 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:08:52 +0000] "POST /api/v1/configurator/service/haproxy-admin/restart HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 07:08:52 pfdeb9dev pfhttpd: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:08:52 +0000] "POST /api/v1/configurator/service/haproxy-admin/restart HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 07:08:56 pfdeb9dev packetfence: INFO pfperl-api(18505): Daemon haproxy-admin took 3.412 seconds to start. (pf::services::manager::launchService)
Apr 14 07:08:56 pfdeb9dev packetfence: INFO pfperl-api(18505): Daemon haproxy-admin took 3.412 seconds to start. (pf::services::manager::launchService)
[..]
Apr 14 07:09:46 pfdeb9dev pfhttpd[18493]: 14/Apr/2020:07:09:46 +0000 [ERROR 499 /api/v1/configurator/service/pf/start] context canceled
Apr 14 07:09:46 pfdeb9dev pfhttpd: 14/Apr/2020:07:09:46 +0000 [ERROR 499 /api/v1/configurator/service/pf/start] context canceled
Apr 14 07:09:46 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:09:46 +0000] "POST /api/v1/configurator/service/pf/start HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 07:09:46 pfdeb9dev pfhttpd: api-frontend-access 127.0.0.1 - - [14/Apr/2020:07:09:46 +0000] "POST /api/v1/configurator/service/pf/start HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
```

It seems to be a minor issue because all services start correctly.

**Comment by nqb** [comment] 2020-04-14 07:40
But `configurator=disabled` is missing in `pf.conf`.

**Comment by julsemaan** [comment] 2020-04-14 11:21
It seems the frontend is not sending an API call to disable the configurator from the logs you've sent

**Comment by nqb** [comment] 2020-04-14 12:03
> It seems the frontend is not sending an API call to disable the configurator from the logs you've sent

Certainly because API returns 504 error code no ?

**Comment by julsemaan** [comment] 2020-04-14 12:21
That seems to be because of an issue with haproxy-admin routing the call to the backend Perl API.

If the Perl API doesn't receive the call to start the service, it would result in the logs you sent so perhaps the haproxy-admin configuration is not generated correctly on Debian

**Comment by julsemaan** [comment] 2020-04-14 12:24
Sorry my comment above is wrong, its the api-frontend that is unable to route the call to the pfperl-api

What is the status of the services after doing this ?

**Comment by cgx** [comment] 2020-04-14 12:26
Let me clarify the configurator part: we disable the configurator if and only if the call to `/api/v1/configurator/service/pf/start` succeeds.

**Comment by nqb** [comment] 2020-04-14 12:37
Ok @cgx, that makes sense and this is why we got this behavior.

@julsemaan, I will check that now.

**Comment by nqb** [comment] 2020-04-14 12:46
`packetfence-api-frontend` is started when I start to use configurator and not restarted after I clicked on "Start PacketFence" button.

Find below output of `journalctl -u packetfence-api-frontend` after I clicked on "Start PacketFence` button:
```
Apr 14 06:20:19 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:19+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:20 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:06:20:20 +0000] "POST /api/v1/configurator/system_service/packetfence-config/restart HTTP/1.1" 200 53 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 06:20:22 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:22+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:24 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:24+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:25 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:06:20:25 +0000] "POST /api/v1/configurator/service/pf/update_systemd HTTP/1.1" 200 49 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 06:20:25 pfdeb9dev pfhttpd[18493]: 14/Apr/2020:06:20:25 +0000 [ERROR 499 /api/v1/configurator/service/haproxy-admin/restart] context canceled
Apr 14 06:20:25 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:06:20:25 +0000] "POST /api/v1/configurator/service/haproxy-admin/restart HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 06:20:27 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:06:20:27 +0000] "GET /api/v1/configurator/config/system/hostname HTTP/1.1" 200 33 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 06:20:28 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:28+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:30 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:30+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:32 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:32+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:34 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:34+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:36 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:36+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:38 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:38+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:40 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:40+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:42 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:42+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:44 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:44+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:46 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:46+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:48 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:48+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:50 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:50+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:52 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:52+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:54 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:54+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 06:20:56 pfdeb9dev api-frontend[18493]: t=2020-04-14T06:20:56+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:20 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:20+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:21 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:21 +0000] "GET /api/v1/queues/stats HTTP/1.1" 401 60 "-" "Go-http-client/1.1"
Apr 14 12:41:21 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:21+0000 lvl=info msg="API login for user system for tenant 0" pid=18493 request-uuid=3e8133ac-7e4d-11ea-8165-525400562cf3
Apr 14 12:41:21 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:21 +0000] "POST /api/v1/login HTTP/1.1" 200 76 "-" "Go-http-client/1.1"
Apr 14 12:41:21 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:21 +0000] "GET /api/v1/queues/stats HTTP/1.1" 200 853 "-" "Go-http-client/1.1"
Apr 14 12:41:22 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:22+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:24 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:24+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:26 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:26+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:28 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:28+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:28 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:28 +0000] "GET /api/v1/queues/stats HTTP/1.1" 200 853 "-" "Go-http-client/1.1"
Apr 14 12:41:30 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:30+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:32 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:32+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:34 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:34+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:36 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:36+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:36 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:36 +0000] "GET /api/v1/dhcp/stats HTTP/1.1" 200 218 "-" "Go-http-client/1.1"
Apr 14 12:41:38 pfdeb9dev api-frontend[18493]: t=2020-04-14T12:41:38+0000 lvl=warn msg="Couldn't acquire lock for pfconfig pool" pid=18493 request-uuid=a4cc9d09-7e17-11ea-8165-525400562cf3
Apr 14 12:41:39 pfdeb9dev pfhttpd[18493]: 14/Apr/2020:12:41:39 +0000 [ERROR 499 /api/v1/configurator/service/pf/start] context canceled
Apr 14 12:41:39 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:39 +0000] "POST /api/v1/configurator/service/pf/start HTTP/1.1" 499 5 "https://pfdeb9dev.lan:1443/admin/alt" "Mozilla/5.0 (X11; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"
Apr 14 12:41:41 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:41 +0000] "GET /api/v1/queues/stats HTTP/1.1" 200 853 "-" "Go-http-client/1.1"
Apr 14 12:41:41 pfdeb9dev pfhttpd[18493]: api-frontend-access 127.0.0.1 - - [14/Apr/2020:12:41:41 +0000] "GET /api/v1/queues/stats HTTP/1.1" 200 853 "-" "Go-http-client/1.1"
```

**Comment by julsemaan** [comment] 2020-04-14 12:47
Can you provide the status of all the services, its the pfperl-api that seems to be dead, the api-frontend is there and alive unable to talk with the backend

**Comment by nqb** [comment] 2020-04-14 13:00
https://gist.github.com/nqb/4e3bacbb9da6f25d55f83159ff1b5c37

**Comment by julsemaan** [comment] 2020-04-14 13:05
It seems the service start has succeeded, is it possible that this took a lot of time because your machine lacks CPU or memory resources

That could have caused your browser to timeout on the request (and cause a context canceled)
Or your browser could have cancelled the request for another reason like a refresh or another reason browsers could cancel requests

**Comment by nqb** [comment] 2020-04-14 14:04
> is it possible that this took a lot of time because your machine lacks CPU or memory resources

Machine is running with 6GB of RAM and one vCPU, I can try to increase.

**Comment by julsemaan** [comment] 2020-04-14 14:06
1 vCPU during service startup is probably your issue, there are many processes that are attempting to start at the same time to speed up the process and with 1 CPU, nothing can be parallelized as the generateconfig usually takes a full CPU during the startup of each service

**Comment by fdurand** [comment] 2020-04-14 20:13
I did the test on my debian setup and i am not able to reproduce.

**Comment by extrafu** [comment] 2020-04-14 20:14
Let's close it for now then, thanks!

**Closed as completed by extrafu** 2020-04-14 20:14 UTC
Labels: Type: Bug, Priority: Low
