### ISSUE TITLE
iptables rules for parking

### ISSUE THREAD

**Issue by whitx** [inverse-inc/packetfence#1681] opened 2016-08-29 19:41 UTC
While using the iptables rule for parking :
-A input-internal-vlan-if --protocol tcp --match tcp --dport 5252 --jump ACCEPT
it is not taken into account (doesn't seems to be everywhere (centos6 only for what I experienced))
in the meantime replace with
-I INPUT --protocol tcp --match tcp --dport 5252 --jump ACCEPT

**Comment by julsemaan** [comment] 2016-08-30 13:27
Seems this is also generalized to all chains as changing the ACCEPT on 1813 for the management chain to a DROP will keep it as an accept.

Hard to say whats causing this, maybe a routing rule that bypasses the chains

**Comment by dwlfrth** [comment] 2016-09-15 17:48
`iptables -nvL` on a "bogus" system please.

**Comment by dwlfrth** [comment] 2016-09-15 18:30
May have found the cause.
At first, we are doing a REDIRECT in the "nat" table to change port 80/443 to 5252
iptables REDIRECT modify destination host to be "127.0.0.1"

Then, we hit the "input" chain of the "filter" table where we try to match with destination host "interface ip" to send to the custom "input-internal-vlan-if" chain where the 5252 ACCEPT is located. That never happens since the destination host is 127.0.0.1 and not the interface ip.

Need to test

**Comment by dwlfrth** [comment] 2016-09-15 18:36
Not sure about @julsemaan comment regarding the RADIUS acct on management tho...

**Comment by julsemaan** [comment] 2016-09-15 19:08
The same environment you looked at had the accounting 1813 issue in case you want to look into it. Otherwise, it could be a corner case or something that came out of my imagination

**Comment by dwlfrth** [comment] 2016-09-15 20:18
Issue is actually coming from
ACCEPT     all  --  \*      \*       0.0.0.0/0            0.0.0.0/0           state RELATED,ESTABLISHED

**Comment by julsemaan** [comment] 2016-09-15 22:35
Sounds like you are right. Small amount of research gave me that iptables tracks UDP connections by src+dst host/port which are often the same for auth + acct as the controllers tend to use the same src port constantly. That makes it that the connection hits that rule in the global input chain and ignores the drop in the management input chain

So it isn't part of that bug, we should probably just document internally how to flush the connection states (if that is a good idea)

**Comment by extrafu** [comment] 2016-10-04 16:23
What's the status on this?

**Comment by dwlfrth** [comment] 2016-10-04 16:26
Waiting for #1720 to be reviewed and merged.

**Closed as completed** 2016-10-04 17:06 UTC
Labels: Type: Bug
