### ISSUE TITLE
v9-gui: creating a node manually fails

### ISSUE THREAD

**Issue by extrafu** [inverse-inc/packetfence#4137] opened 2019-03-27 19:35 UTC
Example:

```
127.000.000.001.45576-127.000.000.001.08080: POST /api/v1/nodes HTTP/1.1
Host: 172.20.100.2:1443
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/72.0.3626.121 Safari/537.36
Content-Length: 108
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en
Authorization: Bearer 12a332f3dfd3c231a66a9cad889d0abfa97b6ce3face1982a80638bf8208bac2
Cache-Control: no-cache
Content-Type: application/json;charset=UTF-8
Cookie: pfappserver_session=f68f6b80a996afb55bed4cf11616708c4ed3c05b
Origin: https://172.20.100.2:1443
Pragma: no-cache
Referer: https://172.20.100.2:1443/admin/alt
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: 172.20.100.2:1443
X-Forwarded-Proto: https
X-Forwarded-Server: pocketfence.inverse.ca
X-Packetfence-Admin-Roles: ALL
X-Real-Ip: 127.0.0.1

{"mac":"00:0a:f5:5f:d0:10","status":"unreg","category":"3","unregdate":"2019-03-28 15:32:32","notes":"toto"}
write error to stdout

127.000.000.001.08080-127.000.000.001.45576: HTTP/1.1 500 Internal Server Error
Content-Type: text/html;charset=UTF-8
Date: Wed, 27 Mar 2019 19:33:32 GMT
Content-Length: 810
Server: Mojolicious (Perl)

<!DOCTYPE html>
<html>
  <head><title>Server error</title></head>
  <style>
      body { background-color: #caecf6 }
      #raptor {
        background: url(/mojo/failraptor.png);
        height: 488px;
        left: 50%;
        margin-left: -371px;
        margin-top: -244px;
        position:absolute;
        top: 50%;
        width: 743px;
      }
    </style>
  <body><div id="raptor"></div></body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by satkunas** [comment] 2019-04-08 23:32
Currently unable to reproduce. Likely fixed in another issue.

Re-assigning to @lzammit for a 3rd-party retest.

**Comment by satkunas** [comment] 2019-04-12 13:22
@cgx can you please test?

**Comment by cgx** [comment] 2019-04-12 15:49
It works.

**Closed as completed by cgx** 2019-04-12 15:49 UTC
Labels: Priority: High
