### ISSUE TITLE
v12: unreg a device manually generate two Disconnect Request

### ISSUE THREAD

**Issue by nqb** [inverse-inc/packetfence#7150] opened 2022-08-25 21:45 UTC
**Describe the bug**
If you edit a node, unreg it and set role to "No role" then save: there is two Disconnect Requests generated and visible in RADIUS Audit log.

One is working, the second one is rejected by network device.

Logs:

```
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(18) INFO: [mac:[undef]] re-evaluating access (admin_modify called) (pf::enforcement::reevaluate_access)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(16) INFO: [mac:[undef]] re-evaluating access (admin_modify called) (pf::enforcement::reevaluate_access)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(16) INFO: [mac:[undef]] Instantiate profile catch_wired_mac_authentication (pf::Connection::ProfileFactory::_from_profile)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(16) INFO: [mac:[undef]] VLAN reassignment is forced. (pf::enforcement::_should_we_reassign_vlan)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(16) INFO: [mac:[undef]] switch port is (172.18.200.201) ifIndex 8connection type: Wired MAC Auth (pf::enforcement::_vlan_reevaluation)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(18) INFO: [mac:[undef]] Instantiate profile catch_wired_mac_authentication (pf::Connection::ProfileFactory::_from_profile)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(18) INFO: [mac:[undef]] VLAN reassignment is forced. (pf::enforcement::_should_we_reassign_vlan)
Aug 25 21:38:07 pfel8dev pfperl-api-docker-wrapper[146623]: pfperl-api(18) INFO: [mac:[undef]] switch port is (172.18.200.201) ifIndex 8connection type: Wired MAC Auth (pf::enforcement::_vlan_reevaluation)
Aug 25 21:38:08 pfel8dev pfqueue[168140]: pfqueue(168140) INFO: [mac:00:03:00:11:11:01] deauthenticating (pf::Switch::Template::radiusDisconnect)
Aug 25 21:38:08 pfel8dev pfqueue[168141]: pfqueue(168141) INFO: [mac:00:03:00:11:11:01] deauthenticating (pf::Switch::Template::radiusDisconnect)
Aug 25 21:38:08 pfel8dev pfqueue[168140]: pfqueue(168140) WARN: [mac:00:03:00:11:11:01] Warning: 1366: Incorrect string value: '\xB8\xA1\xA5}vk...' for column `pf`.`radius_audit_log`.`radius_reply` at row 1 (pf::dal::db_execute)
Aug 25 21:38:08 pfel8dev pfqueue[168141]: pfqueue(168141) WARN: [mac:00:03:00:11:11:01] Warning: 1366: Incorrect string value: '\xBB4U\xCCp\xA0...' for column `pf`.`radius_audit_log`.`radius_reply` at row 1 (pf::dal::db_execute)
Aug 25 21:38:08 pfel8dev pfqueue[168141]: pfqueue(168141) WARN: [mac:00:03:00:11:11:01] Unable to perform RADIUS Disconnect-Request. Disconnect-NAK received with Error-Cause: Session-Context-Not-Found. (pf::Switch::Template::radiusDisconnect)
```

**To Reproduce**
1. Edit a node
1. Remove role and switch status from Registered to Unregistered through web admin
2. Save 

**Expected behavior**
One disconnect request.

**Additional context**
* Tested on EL8.
* Certainly related to recent changes because I didn't see that behavior this week.

**Comment by julsemaan** [comment] 2022-08-30 23:46
There are 2 PATCH API requests being sent with what looks like the same payload. Since they are sent at the very same time, the state reg->unreg gets detected in both requests.

@satkunas, can you clarify why there are 2 PATCH requests when saving a node? Anytime I'm saving a node, it happens (so not just when changing stuff)

Ex:
![image](https://user-images.githubusercontent.com/3857942/187562864-8ea4a75a-617d-4c5c-b6ab-4d9b45794cfe.png)

**Comment by satkunas** [comment] 2022-08-31 12:32
I was able to reproduce with FireFox only.

A fix has been provided in https://github.com/inverse-inc/packetfence/commit/f6956c735c9c8ab4d01549dfa7301820544e0e5a

**Comment by nqb** [comment] 2022-08-31 12:52
I will retest and close if everything is fine.

**Comment by julsemaan** [comment] 2022-08-31 14:52
It did work fine on my end now with the fix.

Leaving opened in case @nqb wants to confirm it on his end too

**Closed as completed** 2022-08-31 18:26 UTC
Labels: Type: Bug, Priority: Medium
