### ISSUE TITLE
Aruba web auth location log issue

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#6387] opened 2021-06-03 20:17 UTC
By default the Aruba web authentication does not update the location log table based out of the HTTP request:

````
sub parseExternalPortalRequest {
    my ( $self, $r, $req ) = @_;
    my $logger = $self->logger;

    # Using a hash to contain external portal parameters
    my %params = ();

    %params = (
        switch_id               => defined($req->param('switchip')) ? $req->param('switchip') : $req->param('apname'),
        client_mac              => clean_mac($req->param('mac')),
        client_ip               => $req->param('ip'),
        ssid                    => $req->param('essid'),
        redirect_url            => $req->param('url'),
        synchronize_locationlog => $FALSE,
        connection_type         => $WEBAUTH_WIRELESS,
    );

    return \%params;
}
````

any particular reason for:

````
    synchronize_locationlog => $FALSE,
````

It create an issue if you device does 802.1x and then connect on an open SSID. PF will only display the last known location at the 802.1x.

**Comment by fdurand** [comment] 2021-12-13 19:47
I think it was before we received a radius request before the device hit the portal so it´s why we set to FALSE.
Now there is some device that hit the portal without any previous radius so it make sense to set to TRUE now.
@julsemaan any thought ?

**Comment by julsemaan** [comment] 2021-12-14 13:33
The sad thing about Aruba is that they have multiple ways of doing the webauth AFAIK

There is one that is RADIUS based (like Cisco) where you apply an ACL that creates the redirection, and one that starts with an HTTP redirection where the web-auth is pinned on the SSID configuration.

But I think there is technically nothing wrong about setting it to TRUE for both cases unless you're relying on the switch overlay (AP MAC based configuration) because you'll lose that info when syncing the locationlog because the switch_mac is not being extracted

**Comment by nqb** [comment] 2022-05-31 08:19
During a customer deployment on Aruba, I got similar issue.

I expected to received a NoEAP request before receiving a WebAuth request but it never occured. Certainly related to Aruba configuration which was a pure WebAuth configuration. So I decided to set `synchronize_locationlog` to `TRUE` and it works better. I was able to catch WebAuth requests using a connection profile with following filter:

`filter=connection_type:Wireless-Web-Auth,ssid:Guest-test`

@julsemaan, tell me if I'm wrong but if we set it to `TRUE` by default and a user/customer is using first implementation (RADIUS based), a connection profile with a filter like:

`filter=connection_type:Wireless-802.11-NoEAP,ssid:Guest-test`

will not match anymore WebAuth requests which could lead to unexpected behavior. For example, hits on a different connection profile.

To handle this use case, we can still add a note in our upgrade guide and document only one way to setup WebAuth using HTTP redirection. I can take care of that.

Let me know what you think.

**Comment by julsemaan** [comment] 2022-05-31 18:19
@nqb, you're right, this could lead to unexpected behavior for customers who do currently have it RADIUS enabled before the webauth kicks in.

The thing with the Aruba webauth is that we don't seem to have a standard way of configuring it (with or without the RADIUS at the beginning). I think we should aim to have proper documentation on configuring it with PF that makes it so we have RADIUS at the beginning too (like Cisco/Meraki) and make our different users use webauth the same way. Not only to fix this issue but to standardize the way they work to make it easier on us to support it.

Adding more workarounds for both mechanisms to work may lead to other corner-case side effects like @nqb pointed out.

**Comment by nqb** [comment] 2022-06-02 08:54
@julsemaan, if I summarize things to do to close this issue:
- add in your documentation a standard way to setup Aruba WebAuth using RADIUS based approach (like Cisco/Meraki)
- keep Aruba.pm as is (without changing `synchronize_locationlog` setting)

For setup patched like @lzammit reported in this issue, we should be careful when upgrading.

**Comment by julsemaan** [comment] 2022-06-02 12:11
> @julsemaan, if I summarize things to do to close this issue:
> 
> * add in your documentation a standard way to setup Aruba WebAuth using RADIUS based approach (like Cisco/Meraki)
> * keep Aruba.pm as is (without changing `synchronize_locationlog` setting)
> 
> For setup patched like @lzammit reported in this issue, we should be careful when upgrading.

That's what I had in mind.

For setups like @lzammit described, I think we could keep it as a custom patch but aim at standardizing it with our official documentation so that it stops being custom at some point.

I also thought of another idea which is that we could also have an option in the switch entry that allows to control whether or not we sync the locationlog in that context but IMO that's exposing very low level behavior to users.

**Comment by nqb** [comment] 2023-01-18 13:38
I think the documentation is a long-term fix.
As a short-term, I suggest to create a dedicated Perl module which override `parseExternalPortalRequest` with `synchronize_locationlog => $TRUE` to hande WebAuth requests without RADIUS.

Let me know what you think.

**Comment by julsemaan** [comment] 2023-01-20 12:45
The new module idea works for me. We just need to make sure it's purpose is documented at least in the PerlDoc of the module (and probably link to here)

**Closed as completed** 2023-01-26 14:36 UTC
Labels: Type: Bug, Priority: High
