### ISSUE TITLE
Admin: Issue with authentication source wasn't found

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#1925] opened 2016-12-21 13:37 UTC
When modifying an authentication source rule, if when you save the rule and the validation doesn't pass, then all the future attempts to save will fail.

Then after this, I'll get an occasional 'The authentication source wasn't found' when continuing to edit the sources

Steps to replicate:
- Clear cache 'bin/pfcmd cache configfiles clear' and restart admin
- Go in Configuration->Sources
- Edit the sms source
- Edit the catchall rule
- Add 'Role -> default' in the actions so there is a double role
![image](https://cloud.githubusercontent.com/assets/3857942/21391221/b656edb6-c758-11e6-9fe4-7e51c4a161d5.png)

- Try to save the rule, it will say 'You can't have more than one action of the same type.'
- Remove the double role action and save again and it will say 'The authentication source wasn't found'
- Navigate the authentication sources and get an occasional 'The authentication source wasn't found'

Logs in trace starting from the save of the catchall rule:
http://pastebin.com/RYEjnPfH

Catalyst log starting from the save of the catchall rule:
http://pastebin.com/nhBp2CnS

This seems to be happening consistently on my setup since pf::config::cached was removed

This is using the latest devel (1af8c141f8905539bfca14ed8f4ba954be59d7fa)

**Comment by jrouzierinverse** [comment] 2016-12-21 15:27
The problem is that with sources.
We do not use the config file as the source of truth.
We are using a mix of pfconfig and some global variables.
It is time rewrite the controller for the sources.

**Comment by extrafu** [comment] 2017-01-18 13:37
Bump

**Comment by jrouzierinverse** [comment] 2017-01-18 18:04
To normalize the auth source configuration was a lot to chew at this point in time.

I fixed the issue in 20ad00368aa726676383b07ffa274fa12fa74c87.

However there is still an issue of the conf/authentication.conf is out of sync with pfconfig.

However to fix it correctly I do not think I have enough time to do so for the next release.

**Comment by julsemaan** [comment] 2017-01-19 19:59
Was able to modify sources without issues.

Will move it to the 6.6 milestone for the controller rewrite but the band-aid looks good

**Comment by julsemaan** [comment] 2017-01-20 16:19
I was able to get that bug again consistently

But now instead of being on the source modification, it is on the creation

Steps:
- Go in 'Configuration->Sources'
- Create a source of type AD
- Configure like this:
![image](https://cloud.githubusercontent.com/assets/3857942/22156635/34090c6a-df02-11e6-9078-00a6835292b4.png)
- Contemplate error

Nothing really meaningful I could see in the admin logs

**Comment by julsemaan** [comment] 2017-01-23 14:50
@jrouzierinverse 

Anything else required for fixing that from me ?

This is a release stopper and a pain to test all cases so it would be nice if we could have the fix ASAP

**Comment by jrouzierinverse** [comment] 2017-01-23 15:05
This is fixed by 83b39af7e0b09960ecaa107580fc7af537cb5e0a

**Comment by julsemaan** [comment] 2017-01-23 15:33
Seems to be working, re-moving to 6.6

**Closed as completed** 2017-06-16 16:02 UTC
Labels: Type: Bug
