### ISSUE TITLE
Wired web auth connection type not working

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#5845] opened 2020-09-28 14:06 UTC
PF version:
````
packetfence-10.1.9-20200925204414.195286781.0007.devel.el7.x86_64
````

Logs:
````
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] handling radius autz request: from switch_ip => (192.168.126.253), connection_type => Ethernet-NoEAP,switch_mac => (5c:50:15:c2:eb:0b), mac => [00:e0:4c:68:09:e3], port => 10111, username => "00e04c6809e3" (pf::radius::authorize)
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] is of status unreg; belongs into registration VLAN (pf::role::getRegistrationRole)
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] (192.168.126.253) Added role registration to the returned RADIUS Access-Accept (pf::Switch::returnRadiusAccessAccept)
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] Adding web authentication redirection to reply using role: 'registration' and URL: 'http://192.168.126.110/Cisco::Catalyst_2960/sid2d9d79' (pf::Switch::Cisco::Catalyst_2960::returnRadiusAccessAccept)
Sep 28 10:02:10 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) INFO: [mac:00:e0:4c:68:09:e3] Updating locationlog from accounting request (pf::api::handle_accounting_metadata)
Sep 28 10:02:13 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) WARN: [mac:00:e0:4c:68:09:e3] Unable to pull accounting history for device 00:e0:4c:68:09:e3. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Sep 28 10:02:13 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) WARN: [mac:00:e0:4c:68:09:e3] Unable to pull accounting history for device 00:e0:4c:68:09:e3. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Sep 28 10:02:20 pf-testing pfqueue: pfqueue(30024) WARN: [mac:00:e0:4c:68:09:e3] Unable to pull accounting history for device 00:e0:4c:68:09:e3. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Sep 28 10:02:34 pf-testing pfqueue: pfqueue(30010) WARN: [mac:00:e0:4c:68:09:e3] Unable to match MAC address to IP '192.168.126.199' (pf::ip4log::ip2mac)
Sep 28 10:02:35 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) WARN: [mac:00:e0:4c:68:09:e3] Unable to pull accounting history for device 00:e0:4c:68:09:e3. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Sep 28 10:02:35 pf-testing packetfence_httpd.aaa: httpd.aaa(29582) WARN: [mac:00:e0:4c:68:09:e3] Unable to pull accounting history for device 00:e0:4c:68:09:e3. The history set doesn't exist yet. (pf::accounting_events_history::latest_mac_history)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30347) INFO: [mac:00:e0:4c:68:09:e3] External captive portal detected ! (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30347) INFO: [mac:00:e0:4c:68:09:e3] Detected external portal client. Using the IP 192.168.126.199 address in it's session. (captiveportal::PacketFence::Model::Portal::Session::_build_clientIP)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30347) INFO: [mac:00:e0:4c:68:09:e3] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30348) INFO: [mac:00:e0:4c:68:09:e3] External captive portal detected ! (captiveportal::PacketFence::Model::Portal::Session::_build_dispatcherSession)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30348) INFO: [mac:00:e0:4c:68:09:e3] Detected external portal client. Using the IP 192.168.126.199 address in it's session. (captiveportal::PacketFence::Model::Portal::Session::_build_clientIP)
Sep 28 10:02:41 pf-testing packetfence_httpd.portal: httpd.portal(30348) INFO: [mac:00:e0:4c:68:09:e3] Instantiate profile default (pf::Connection::ProfileFactory::_from_profile)
````

Conf:
````
[Wired-web-auth]
locale=
sources=users
advanced_filter=
filter=connection_type:Ethernet-Web-Auth
````

**Comment by julsemaan** [comment] 2020-09-28 14:20
this is a duplicate of #4816

**Closed as completed by julsemaan** 2020-09-28 14:20 UTC
Labels: Type: Bug, Priority: Medium
