### ISSUE TITLE
Email Templates - contain no data when emailed - guest/sponsor signup

### ISSUE THREAD

**Issue by burrellzone** [inverse-inc/packetfence#3949] opened 2019-01-22 05:50 UTC
Email Templates - contain no data when emailed - guest/sponsor signup

We have a guest Signup process with sponsor validation.

When users signup for guest access, emails are being sent and do arrive in the users mailboxes. However they are blank and contain no user data and or hyperlink to confirm registration. (see pic)
"Activate Acess" button is blank and you cannot click on it.

This was working in version 8.2 but since upgrading to 8.3 this does not work.
We have also re-installed a new server from scratch from ZEN  and the same behaviour is happening in 8.3 with the email templates and zero data.
Please would someone take a look and advise on this.
Many thanks

<img width="597" alt="pf-guest reg-no-data" src="https://user-images.githubusercontent.com/38036879/51514787-f54d2480-1e19-11e9-8d3b-48e530c57818.png">

**Comment by nqb** [comment] 2019-01-22 16:40
Duplicate of #3948

**Closed as completed by nqb** 2019-01-22 16:40 UTC
