### ISSUE TITLE
Editing switches, users, auth sources, conn. profiles is extremely slow in new admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4697] opened 2019-07-30 14:06 UTC
**Describe the bug**
When configuring a switch, typing in the text fields is extremely slow 

**To Reproduce**
1. Create a new switch
2. Type in the description field
3. Go grab a coffee
4. Your description has been populated successfully

**Expected behavior**
Better responsiveness of the text fields

**Comment by extrafu** [comment] 2019-08-28 14:40
@cgx and @satkunas Please test this together and try to find if we can optimize things.

**Comment by cgx** [comment] 2019-08-30 01:12
@satkunas I wonder if the [lazy attribute](https://vuejs.org/v2/guide/forms.html#lazy) could help. 🤔

**Comment by nqb** [comment] 2019-11-07 12:17
Hello,

I got same behavior for a customer running PF 9.0.1 after applying maintenance patches (not the case before I applied maintenance patches). 

Issue is not only related to switches. I got same behavior when editing:
- an user already created
- an authentication source already created
- a connection profile already created

I'm able to reproduce issue on nightly builds, I got following message in web browser console:
![Capture d’écran de 2019-11-07 13-11-33](https://user-images.githubusercontent.com/10830260/68388265-82225e00-0160-11ea-89db-1078500882c6.png)

**Comment by nqb** [comment] 2019-11-07 12:23
In order to identify which commit has caused regression, I list commits applied on my PF 9.0.1 setup:

https://github.com/inverse-inc/packetfence/compare/4d4f7ba3a77db5e238b351133d36f1d5e5fc8232...edf2d66bbc8d1bcab3874cb5ca0a532ca5eee2fc

**Comment by nqb** [comment] 2019-11-07 12:24
@cgx and @satkunas,

Do you see a commit that can cause this behavior ?

**Comment by nqb** [comment] 2019-11-07 12:42
Customer just informed me that he gots this behavior **before** I applied maintenance patches. So it doesn't seems related to maintenance patches. 

From my point of view, we should try to fix this issue before releasing 9.2

**Comment by julsemaan** [comment] 2019-11-07 12:51
I totally agree, this has been going on for way too long, its been like this since the initial release of 9.0

**Comment by nqb** [comment] 2019-11-07 13:33
I moved milestone to 9.2 to be sure we don't skip it.

**Comment by nqb** [comment] 2019-11-25 06:36
@extrafu, any reason you change milestone for this issue ?

From my point of view, we should fix this issue for 9.2. Editing items mentioned here is really painful with this bug. I'm putting back 9.2 milestone, feel free to change it.

**Comment by extrafu** [comment] 2019-11-25 12:24
We'll have to push it to v9.3 - it requires too much work for 9.2. We should make it available in the maintenance nonetheless if possible.

**Comment by nqb** [comment] 2019-11-27 13:00
I set this issue with a high priority because another customer is impacted by this behavior.

**Comment by nqb** [comment] 2020-01-08 13:28
I don't see a real improvement on this issue with merge of #4978 when I'm creating a new rule on a source or when I'm trying to edit a user.

**Comment by julsemaan** [comment] 2020-01-08 20:26
I feel its much faster personally in those 2 pages.

Can you expand on what parts of those are still slow

**Comment by nqb** [comment] 2020-01-09 11:12
@julsemaan: you're right.

**Comment by extrafu** [comment] 2020-01-09 20:01
I guess we can now close this.

**Closed as completed by extrafu** 2020-01-09 20:01 UTC
Labels: Type: Bug, Priority: High
