### ISSUE TITLE
iptables: catch all the dns traffic from the registration network

### ISSUE THREAD

**Issue by lzammit** [inverse-inc/packetfence#2407] opened 2017-06-16 17:11 UTC
It will be nice to catch the dns traffic in the registration network and forward it to pfdns.

It will solve the issue in Layer2 where the devices are  configured with a static dns entry.

**Comment by julsemaan** [comment] 2017-06-16 17:36
It would seem you really **really** want this as you opened #2381 that says the exact same thing 11 days ago

**Comment by dwlfrth** [comment] 2017-06-16 18:39
Closed, won't fix since it's a duplicate of #2381 AKA Zammitbug

**Closed as completed by dwlfrth** 2017-06-16 18:39 UTC
Labels: zammitbug

**Comment by lzammit** [comment] 2017-06-16 20:27
Ok.
