### ISSUE TITLE
Portal module set role action

### ISSUE THREAD

**Issue by fdurand** [inverse-inc/packetfence#5912] opened 2020-10-13 15:38 UTC
**Describe the bug**
When you set a "set_role" action in a portal module, the value saved in the configuration file is the id of the role and not the role itself.

**Screenshots**

![image](https://user-images.githubusercontent.com/1553962/95883050-72d06b00-0d48-11eb-9849-1c879f1bfae0.png)

![image](https://user-images.githubusercontent.com/1553962/95883113-88459500-0d48-11eb-8e6e-ecd1ffa4d976.png)

**Expected behavior**
Should be the role name

**Comment by jrouzierinverse** [comment] 2020-10-13 17:10
It looks like the frontend is sending the role id instead of the name.
@satkunas the action.item.properties.value is just a plain text field.
Do you want to me add the sibling attribute in action.item.properties.type?
Or are you going to handle that in the frontend?

**Comment by jrouzierinverse** [comment] 2020-10-13 17:33
@satkunas I added the siblings can you update the frontend.

**Comment by nqb** [comment] 2020-10-14 05:52
This issue is a duplicate of #5133

**Closed as completed** 2021-08-04 12:43 UTC
Labels: Type: Bug, Priority: High
