### ISSUE TITLE
Failed to create a local user that only has admin access

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#5772] opened 2020-08-27 15:24 UTC
**Describe the bug**
I tried to create a local user that only has an admin right and it failed with this error:
```
Aug 27 11:21:28 executor packetfence: pfperl-api(26909) ERROR: Database query failed with non retryable error: Column 'category' cannot be null (errno: 1048) [INSERT INTO `password` ( `access_duration`, `access_level`, `category`, `expiration`, `login_remaining`, `password`, `pid`, `sponsor`, `tenant_id`, `valid_from`) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )]{N
ULL, Node Manager,Security Event Manager, NULL, 2037-01-01, NULL, {ntlm}1B17818004EFF64891B90A046ACDCE54, jsemaan-test-admin-rights, inverse, 1, 2020-08-27} (pf::dal::db_execute)
```

**To Reproduce**
1. Create a local user that has only an "Access level" action

**Expected behavior**
Should be able to create a local user without having to specify all the actions like role and unregdate

This is on 10.1

**Comment by jrouzierinverse** [comment] 2020-08-27 15:51
This is a duplicate of #5732 
Can you run the following SQL ```DESC password;```?
Because the column category is allowed to be null on the password table.

**Comment by julsemaan** [comment] 2020-08-27 17:26
```
MariaDB [pf]> desc password;
+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| tenant_id       | int(11)      | NO   | PRI | 1                   |       |
| pid             | varchar(255) | NO   | PRI | NULL                |       |
| password        | varchar(255) | NO   |     | NULL                |       |
| valid_from      | datetime     | NO   |     | 0000-00-00 00:00:00 |       |
| expiration      | datetime     | NO   |     | NULL                |       |
| access_duration | varchar(255) | YES  |     | NULL                |       |
| access_level    | varchar(255) | YES  |     | NONE                |       |
| category        | int(11)      | NO   |     | NULL                |       |
| sponsor         | tinyint(1)   | NO   |     | 0                   |       |
| unregdate       | datetime     | NO   |     | 0000-00-00 00:00:00 |       |
| login_remaining | int(11)      | YES  |     | NULL                |       |
+-----------------+--------------+------+-----+---------------------+-------+
11 rows in set (0.01 sec)
```

**Comment by jrouzierinverse** [comment] 2020-08-27 17:33
For some reason, the category is NOT NULL.

```
MariaDB [pf_smoke_test]> DESC password;
+-----------------+--------------+------+-----+---------------------+-------+
| Field           | Type         | Null | Key | Default             | Extra |
+-----------------+--------------+------+-----+---------------------+-------+
| tenant_id       | int(11)      | NO   | PRI | 1                   |       |
| pid             | varchar(255) | NO   | PRI | NULL                |       |
| password        | varchar(255) | NO   |     | NULL                |       |
| valid_from      | datetime     | NO   |     | 0000-00-00 00:00:00 |       |
| expiration      | datetime     | NO   |     | NULL                |       |
| access_duration | varchar(255) | YES  |     | NULL                |       |
| access_level    | varchar(255) | YES  |     | NONE                |       |
| category        | int(11)      | YES  |     | NULL                |       |
| sponsor         | tinyint(1)   | NO   |     | 0                   |       |
| unregdate       | datetime     | NO   |     | 0000-00-00 00:00:00 |       |
| login_remaining | int(11)      | YES  |     | NULL                |       |
+-----------------+--------------+------+-----+---------------------+-------+
```

**Comment by julsemaan** [comment] 2020-08-27 17:36
I just connected on a setup that has been upgraded since 3.6.1 and the category is allowed to NULL so this issue is specific to the environment. My guess is that @fdurand was also working on the environment that has this issue but I'll let him close #5732 and will inform him about the issue privately so he can address it at his customer.

**Closed as completed** 2020-08-27 17:36 UTC
Labels: Type: Bug, Priority: High

**Comment by jrouzierinverse** [comment] 2020-08-27 17:39
For some reason, the password table category is no longer NULLABLE.
This should fix it.
```ALTER TABLE password CHANGE COLUMN category category int DEFAULT NULL;```
