### ISSUE TITLE
Unable to remove authentication sources in login portal module

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#4920] opened 2019-11-12 19:23 UTC
**Describe the bug**
I'm unable to remove all the authentication sources of a portal module

**To Reproduce**
1. Create an Authentication::Login portal module and specify a couple of authentication sources
2. Save that portal module
3. Clear the authentication sources
4. Save that portal module
5. Refresh the page and the authentication sources are still there

**Additional context**
From what I can tell the API call is correct (has multi_source_ids:[]) so I'll assign to @jrouzierinverse

**Comment by jrouzierinverse** [comment] 2019-11-12 19:51
@julsemaan please retry.

**Comment by jrouzierinverse** [comment] 2019-11-19 10:50
@fdurand can you test this?

**Comment by satkunas** [comment] 2019-11-21 20:09
I'm unable to reproduce.

**Comment by jrouzierinverse** [comment] 2019-11-21 21:21
Should we close this then?

**Comment by extrafu** [comment] 2019-11-22 15:09
If it's not reproducible, let's close it.

**Closed as completed by extrafu** 2019-11-22 15:09 UTC
Labels: Type: Bug
