### ISSUE TITLE
Creating/modifying/deleting a syslog forwarder should prompt to restart rsyslog in the admin

### ISSUE THREAD

**Issue by julsemaan** [inverse-inc/packetfence#6532] opened 2021-08-20 12:23 UTC
**Describe the bug**
Creating/modifying/deleting a syslog forwarder should prompt to restart rsyslog in the admin

**To Reproduce**
1. Create a new syslog forwarder entry in the admin interface
2. It isn't active until you restart rsyslog via the command line

**Expected behavior**
Like the other admin sections, it should prompt to restart rsyslog when doing an operation on the entry
There is an API call for that:
`pfperl-api get -M POST /api/v1/system_service/rsyslog/restart`

**Comment by nqb** [comment] 2021-08-20 13:29
As mentioned in [our documentation](https://www.packetfence.org/doc/PacketFence_Installation_Guide.html#_syslog_forwarding), you also need to run `/usr/local/pf/bin/pfcmd generatesyslogconfig`.

I don't think we have an API call for that and I think that restarting `rsyslog` will not put your configuration in production.

**Comment by julsemaan** [comment] 2021-08-20 13:59
When you restart rsyslog, it regenerates the configuration

**Comment by satkunas** [comment] 2021-08-20 14:36
@julsemaan The API responses from `/api/v1/system_service/:service/:method` and `/api/v1/service/:service/:method` differ. I won't be able to offer a service button for `rsyslog` that behaves the same as the others until the former API call has some changes made. Since these changes might cause regressions in the configurator I will defer on adding the usual service button for now, and instead offer a single "Regenerate Config" button for the time being.

**Comment by julsemaan** [comment] 2021-08-20 14:37
Lets just put a warning on top of the section like in the `Event loggers`

**Comment by satkunas** [comment] 2021-08-20 14:55
@julsemaan done. I left this issue open so we can reassign the milestone and revisit again later.

**Comment by julsemaan** [comment] 2021-08-23 17:44
Moved the milestone and marked this as a feature instead of a bug

**Comment by satkunas** [comment] 2022-08-25 17:24
A different endpoint (system_service) needs to be used for `rsyslog`, `monit` and `mariadb`.

Don't expose them on the services page.

We can put them in each section that needs them as single-service buttons-only.

**Closed as completed** 2023-01-16 18:08 UTC
Labels: Type: Feature / Enhancement, Priority: Low
